/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int __cdecl opiehash(int *a1, int a2);
// int __cdecl SHA1_Final(_DWORD, _DWORD); weak
// int __cdecl SHA1_Update(_DWORD, _DWORD, _DWORD); weak
// int __cdecl SHA1_Init(_DWORD); weak
// int __cdecl opiemd4final(_DWORD, _DWORD); weak
// int __cdecl opiemd4update(_DWORD, _DWORD, _DWORD); weak
// int __cdecl opiemd4init(_DWORD); weak
// int __cdecl opiemd5final(_DWORD, _DWORD); weak
// int __cdecl opiemd5update(_DWORD, _DWORD, _DWORD); weak
// int __cdecl opiemd5init(_DWORD); weak


//----- (00000000) --------------------------------------------------------
int __cdecl opiehash(int *a1, int a2)
{
  int *v2; // esi
  int result; // eax
  int v4; // ecx
  int v5[2]; // [esp+4h] [ebp-C8h] BYREF
  int v6; // [esp+Ch] [ebp-C0h]
  int v7; // [esp+10h] [ebp-BCh]
  char v8[88]; // [esp+14h] [ebp-B8h] BYREF
  char v9[96]; // [esp+6Ch] [ebp-60h] BYREF

  v2 = a1;
  if ( a2 == 5 )
  {
    opiemd5init(v8);
    opiemd5update(v8, a1, 8);
    opiemd5final(v5, v8);
  }
  else if ( a2 == 6 )
  {
    SHA1_Init(v9);
    v2 = a1;
    SHA1_Update(v9, a1, 8);
    SHA1_Final(v5, v9);
    goto LABEL_4;
  }
  opiemd4init(v8);
  opiemd4update(v8, a1, 8);
  opiemd4final(v5, v8);
LABEL_4:
  result = v6 ^ v5[0];
  v4 = v7 ^ v5[1];
  *v2 = v6 ^ v5[0];
  v2[1] = v4;
  return result;
}
// C0: using guessed type int __cdecl SHA1_Final(_DWORD, _DWORD);
// C4: using guessed type int __cdecl SHA1_Update(_DWORD, _DWORD, _DWORD);
// C8: using guessed type int __cdecl SHA1_Init(_DWORD);
// CC: using guessed type int __cdecl opiemd4final(_DWORD, _DWORD);
// D0: using guessed type int __cdecl opiemd4update(_DWORD, _DWORD, _DWORD);
// D4: using guessed type int __cdecl opiemd4init(_DWORD);
// D8: using guessed type int __cdecl opiemd5final(_DWORD, _DWORD);
// DC: using guessed type int __cdecl opiemd5update(_DWORD, _DWORD, _DWORD);
// E0: using guessed type int __cdecl opiemd5init(_DWORD);

// nfuncs=10 queued=1 decompiled=1 lumina nreq=0 worse=0 better=0
// ALL OK, 1 function(s) have been successfully decompiled
