/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int __cdecl opiekeycrunch(int a1, int *a2, const char *a3, const char *a4);
// int _printf(const char *const Format, ...);
// void __cdecl _free(void *Block);
// int __cdecl SHA1_Final(_DWORD, _DWORD); weak
// int __cdecl SHA1_Update(_DWORD, _DWORD, _DWORD); weak
// int __cdecl SHA1_Init(_DWORD); weak
// int __cdecl opiemd5final(_DWORD, _DWORD); weak
// int __cdecl opiemd5update(_DWORD, _DWORD, _DWORD); weak
// int __cdecl opiemd5init(_DWORD); weak
// int __cdecl opiemd4final(_DWORD, _DWORD); weak
// int __cdecl opiemd4update(_DWORD, _DWORD, _DWORD); weak
// int __cdecl opiemd4init(_DWORD); weak
// void *__cdecl _malloc(size_t Size);


//----- (00000000) --------------------------------------------------------
int __cdecl opiekeycrunch(int a1, int *a2, const char *a3, const char *a4)
{
  unsigned int v4; // kr04_4
  unsigned int v5; // kr08_4
  int v6; // ebp
  char *v7; // ebx
  int v9; // ecx
  int v10[5]; // [esp+10h] [ebp-CCh] BYREF
  char v11[88]; // [esp+24h] [ebp-B8h] BYREF
  char v12[96]; // [esp+7Ch] [ebp-60h] BYREF

  if ( !a3 )
    return 1;
  if ( !*a3 )
    return 1;
  if ( !a4 )
    return 1;
  if ( !a2 )
    return 1;
  v4 = strlen(a3) + 1;
  if ( v4 - 1 > 0x10 )
    return 1;
  v5 = strlen(a4) + 1;
  v6 = v5 - 1 + v4 - 1;
  v7 = (char *)_malloc(v5 + v4 - 1);
  if ( !v7 )
    return -1;
  strcpy(v7, a3);
  strcat(v7, a4);
  switch ( a1 )
  {
    case 4:
      opiemd4init(v11);
      opiemd4update(v11, v7, v6);
      opiemd4final(v10, v11);
LABEL_14:
      _free(v7);
      v9 = v10[3] ^ v10[1];
      *a2 = v10[2] ^ v10[0];
      a2[1] = v9;
      return 0;
    case 5:
      opiemd5init(v11);
      opiemd5update(v11, v7, v6);
      opiemd5final(v10, v11);
      goto LABEL_14;
    case 6:
      SHA1_Init(v12);
      SHA1_Update(v12, v7, v6);
      SHA1_Final(v10, v12);
      goto LABEL_14;
  }
  _printf("not found algorithm\n");
  _free(v7);
  return -1;
}
// 1F8: using guessed type int __cdecl SHA1_Final(_DWORD, _DWORD);
// 1FC: using guessed type int __cdecl SHA1_Update(_DWORD, _DWORD, _DWORD);
// 200: using guessed type int __cdecl SHA1_Init(_DWORD);
// 204: using guessed type int __cdecl opiemd5final(_DWORD, _DWORD);
// 208: using guessed type int __cdecl opiemd5update(_DWORD, _DWORD, _DWORD);
// 20C: using guessed type int __cdecl opiemd5init(_DWORD);
// 210: using guessed type int __cdecl opiemd4final(_DWORD, _DWORD);
// 214: using guessed type int __cdecl opiemd4update(_DWORD, _DWORD, _DWORD);
// 218: using guessed type int __cdecl opiemd4init(_DWORD);

// nfuncs=13 queued=1 decompiled=1 lumina nreq=0 worse=0 better=0
// ALL OK, 1 function(s) have been successfully decompiled
