/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

_DWORD *__cdecl opiemd4init(_DWORD *a1);
unsigned int __cdecl opiemd4update(int *a1, char *a2, unsigned int a3);
int __cdecl opiemd4final(int a1, int a2);
int __cdecl MD4Transform(int *a1, int a2);
void __cdecl Encode(int a1, _BYTE *a2, unsigned int a3);
void __cdecl Decode(int a1, int a2, unsigned int a3);

//-------------------------------------------------------------------------
// Data declarations

char PADDING[64] =
{
  '\x80',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0'
}; // idb


//----- (00000040) --------------------------------------------------------
_DWORD *__cdecl opiemd4init(_DWORD *a1)
{
  _DWORD *result; // eax

  result = a1;
  a1[5] = 0;
  a1[4] = 0;
  *a1 = 1732584193;
  a1[1] = -271733879;
  a1[2] = -1732584194;
  a1[3] = 271733878;
  return result;
}

//----- (00000070) --------------------------------------------------------
unsigned int __cdecl opiemd4update(int *a1, char *a2, unsigned int a3)
{
  unsigned int v3; // ecx
  unsigned int v4; // edx
  int v5; // eax
  unsigned int v6; // ebp
  unsigned int v7; // edi
  unsigned int i; // esi
  unsigned int v9; // ecx
  char *v10; // esi
  char *v11; // edi
  unsigned int result; // eax

  v3 = a3;
  v4 = a1[4] + 8 * a3;
  v5 = ((unsigned int)a1[4] >> 3) & 0x3F;
  a1[4] = v4;
  if ( v4 < 8 * a3 )
    ++a1[5];
  v6 = 64 - v5;
  a1[5] += a3 >> 29;
  if ( a3 < 64 - v5 )
  {
    v7 = 0;
  }
  else
  {
    qmemcpy((char *)a1 + v5 + 24, a2, v6);
    MD4Transform(a1, (int)(a1 + 6));
    v7 = v6;
    for ( i = v6 + 63; i < a3; v7 += 64 )
    {
      MD4Transform(a1, (int)&a2[i - 63]);
      i += 64;
    }
    v3 = a3;
    v5 = 0;
  }
  v9 = v3 - v7;
  v10 = &a2[v7];
  v11 = (char *)a1 + v5 + 24;
  result = v9;
  qmemcpy(v11, v10, v9);
  return result;
}

//----- (00000130) --------------------------------------------------------
int __cdecl opiemd4final(int a1, int a2)
{
  unsigned int v2; // eax
  int v3; // ecx
  int result; // eax
  char v5[8]; // [esp+8h] [ebp-8h] BYREF

  Encode((int)v5, (_BYTE *)(a2 + 16), 8u);
  v2 = (*(_DWORD *)(a2 + 16) >> 3) & 0x3F;
  v3 = 56;
  if ( v2 >= 0x38 )
    v3 = 120;
  opiemd4update((int *)a2, PADDING, v3 - v2);
  opiemd4update((int *)a2, v5, 8u);
  Encode(a1, (_BYTE *)a2, 0x10u);
  result = 0;
  memset((void *)a2, 0, 0x58u);
  return result;
}

//----- (000001A0) --------------------------------------------------------
int __cdecl MD4Transform(int *a1, int a2)
{
  int v3; // esi
  int v4; // ebx
  int v5; // ebp
  unsigned int v6; // esi
  unsigned __int64 v7; // kr00_8
  unsigned int v8; // ebp
  int v9; // ecx
  unsigned int v10; // ebx
  int v11; // edx
  unsigned int v12; // esi
  int v13; // ebx
  unsigned int v14; // eax
  int v15; // esi
  unsigned int v16; // ecx
  int v17; // eax
  unsigned int v18; // edx
  int v19; // ecx
  __int64 v20; // kr08_8
  unsigned int v21; // esi
  int v22; // edx
  unsigned int v23; // eax
  int v24; // esi
  unsigned int v25; // ecx
  int v26; // eax
  __int64 v27; // rcx
  unsigned int v28; // edx
  int v29; // ebp
  unsigned int v30; // esi
  unsigned int v31; // eax
  int v32; // edx
  int v33; // ebp
  unsigned __int64 v34; // kr10_8
  int v35; // eax
  unsigned int v36; // edx
  __int64 v37; // kr18_8
  int v38; // edx
  unsigned int v39; // ebp
  unsigned int v40; // eax
  int v41; // edx
  int v42; // esi
  unsigned int v43; // eax
  int v44; // edx
  int v45; // esi
  unsigned int v46; // eax
  unsigned int v47; // eax
  unsigned int v48; // edx
  unsigned int v49; // esi
  int v50; // edx
  int v51; // esi
  unsigned int v52; // eax
  unsigned int v53; // edx
  unsigned int v54; // esi
  int v55; // edx
  unsigned int v56; // eax
  int v57; // esi
  int v58; // edx
  unsigned int v59; // eax
  int v60; // esi
  int v61; // edx
  unsigned int v62; // eax
  int result; // eax
  int v64; // [esp+10h] [ebp-40h] BYREF
  int v65; // [esp+14h] [ebp-3Ch]
  int v66; // [esp+18h] [ebp-38h]
  int v67; // [esp+1Ch] [ebp-34h]
  int v68; // [esp+20h] [ebp-30h]
  int v69; // [esp+24h] [ebp-2Ch]
  int v70; // [esp+28h] [ebp-28h]
  int v71; // [esp+2Ch] [ebp-24h]
  int v72; // [esp+30h] [ebp-20h]
  int v73; // [esp+34h] [ebp-1Ch]
  int v74; // [esp+38h] [ebp-18h]
  int v75; // [esp+3Ch] [ebp-14h]
  int v76; // [esp+40h] [ebp-10h]
  int v77; // [esp+44h] [ebp-Ch]
  int v78; // [esp+48h] [ebp-8h]
  int v79; // [esp+4Ch] [ebp-4h]
  int v80; // [esp+54h] [ebp+4h]

  v3 = *a1;
  v4 = a1[1];
  v5 = a1[2];
  v80 = a1[3];
  Decode((int)&v64, a2, 0x40u);
  v6 = (8 * (v64 + (v4 & v5 | v80 & ~v4) + v3)) | ((v64 + (v4 & v5 | v80 & (unsigned int)~v4) + v3) >> 29);
  v7 = (unsigned __int64)(v65 + (v6 & v4 | v5 & ~v6) + v80) << 7;
  v8 = v66 + (v6 & (v7 | HIDWORD(v7)) | v4 & ~(v7 | HIDWORD(v7))) + v5;
  v9 = (v8 << 11) | (v8 >> 21);
  v10 = v67 + (v9 & (v7 | HIDWORD(v7)) | v6 & ~v9) + v4;
  v11 = (v10 >> 13) | (v10 << 19);
  v12 = v68 + (v11 & v9 | (v7 | HIDWORD(v7)) & ~v11) + v6;
  v13 = (8 * v12) | (v12 >> 29);
  v14 = v69 + (v13 & v11 | v9 & ~v13) + (v7 | HIDWORD(v7));
  v15 = (v14 << 7) | (v14 >> 25);
  v16 = v70 + (v13 & v15 | v11 & ~v15) + v9;
  v17 = (v16 << 11) | (v16 >> 21);
  v18 = v71 + (v17 & v15 | v13 & ~v17) + v11;
  v19 = (v18 >> 13) | (v18 << 19);
  v20 = 8i64 * (v72 + (v19 & v17 | v15 & (unsigned int)~v19) + v13);
  v21 = v73 + ((v20 | HIDWORD(v20)) & v19 | v17 & ~(v20 | HIDWORD(v20))) + v15;
  v22 = (v21 << 7) | (v21 >> 25);
  v23 = v74 + ((v20 | HIDWORD(v20)) & v22 | v19 & ~v22) + v17;
  v24 = (v23 << 11) | (v23 >> 21);
  v25 = v75 + (v24 & v22 | (v20 | HIDWORD(v20)) & ~v24) + v19;
  v26 = (v25 >> 13) | (v25 << 19);
  v27 = 8i64 * (v76 + (v26 & v24 | v22 & ~v26) + ((unsigned int)v20 | HIDWORD(v20)));
  HIDWORD(v27) |= v27;
  v28 = v77 + (HIDWORD(v27) & v26 | v24 & ~HIDWORD(v27)) + v22;
  v29 = (v28 << 7) | (v28 >> 25);
  v30 = v78 + (HIDWORD(v27) & v29 | v26 & ~v29) + v24;
  LODWORD(v27) = (v30 << 11) | (v30 >> 21);
  v31 = v79 + (v27 & v29 | HIDWORD(v27) & ~(_DWORD)v27) + v26;
  v32 = (v31 >> 13) | (v31 << 19);
  HIDWORD(v27) = (8 * (HIDWORD(v27) + v64 + (v32 & v27 | v29 & (v32 | v27)) + 1518500249)) | ((HIDWORD(v27)
                                                                                             + v64
                                                                                             + (v32 & (unsigned int)v27 | v29 & (v32 | (unsigned int)v27))
                                                                                             + 1518500249) >> 29);
  v33 = (32 * (v68 + (HIDWORD(v27) & v32 | v27 & (HIDWORD(v27) | v32)) + v29 + 1518500249)) | ((v68
                                                                                              + (HIDWORD(v27) & v32 | (unsigned int)v27 & (HIDWORD(v27) | v32))
                                                                                              + v29
                                                                                              + 1518500249) >> 27);
  v34 = (unsigned __int64)((unsigned int)v27 + v72 + (HIDWORD(v27) & v32 | v33 & (HIDWORD(v27) | v32)) + 1518500249) << 9;
  v35 = v34 | HIDWORD(v34);
  v36 = v32 + v76 + (HIDWORD(v27) & v35 | v33 & (HIDWORD(v27) | v35)) + 1518500249;
  LODWORD(v27) = (v36 << 13) | (v36 >> 19);
  v37 = 8i64 * (HIDWORD(v27) + v65 + ((unsigned int)v27 & v35 | v33 & ((unsigned int)v27 | v35)) + 1518500249);
  v38 = v37 | HIDWORD(v37);
  v39 = v69 + (v38 & v27 | (v34 | HIDWORD(v34)) & (v38 | v27)) + v33 + 1518500249;
  HIDWORD(v27) = (32 * v39) | (v39 >> 27);
  v40 = ((v35 + v73 + (v38 & (unsigned int)v27 | HIDWORD(v27) & (v38 | (unsigned int)v27)) + 1518500249) << 9) | ((v35 + v73 + (v38 & (unsigned int)v27 | HIDWORD(v27) & (v38 | (unsigned int)v27)) + 1518500249) >> 23);
  LODWORD(v27) = (((_DWORD)v27 + v77 + (v38 & v40 | HIDWORD(v27) & (v38 | v40)) + 1518500249) << 13) | (((unsigned int)v27 + v77 + (v38 & v40 | HIDWORD(v27) & (v38 | v40)) + 1518500249) >> 19);
  v41 = (8 * (v38 + v66 + (v27 & v40 | HIDWORD(v27) & (v27 | v40)) + 1518500249)) | ((v38
                                                                                    + v66
                                                                                    + ((unsigned int)v27 & v40 | HIDWORD(v27) & ((unsigned int)v27 | v40))
                                                                                    + 1518500249) >> 29);
  HIDWORD(v27) += v70 + (v41 & v27 | v40 & (v41 | v27)) + 1518500249;
  v42 = (32 * HIDWORD(v27)) | (HIDWORD(v27) >> 27);
  v43 = ((v40 + v74 + (v41 & (unsigned int)v27 | v42 & (v41 | (unsigned int)v27)) + 1518500249) << 9) | ((v40 + v74 + (v41 & (unsigned int)v27 | v42 & (v41 | (unsigned int)v27)) + 1518500249) >> 23);
  LODWORD(v27) = (((_DWORD)v27 + v78 + (v41 & v43 | v42 & (v41 | v43)) + 1518500249) << 13) | (((unsigned int)v27
                                                                                              + v78
                                                                                              + (v41 & v43 | v42 & (v41 | v43))
                                                                                              + 1518500249) >> 19);
  v44 = (8 * (v41 + v67 + (v27 & v43 | v42 & (v27 | v43)) + 1518500249)) | ((v41
                                                                           + v67
                                                                           + ((unsigned int)v27 & v43 | v42 & ((unsigned int)v27 | v43))
                                                                           + 1518500249) >> 29);
  v45 = (32 * (v42 + v71 + (v44 & v27 | v43 & (v44 | v27)) + 1518500249)) | ((v42
                                                                            + v71
                                                                            + (v44 & (unsigned int)v27 | v43 & (v44 | (unsigned int)v27))
                                                                            + 1518500249) >> 27);
  v46 = v43 + v75 + (v44 & v27 | v45 & (v44 | v27)) + 1518500249;
  HIDWORD(v27) = (v46 << 9) | (v46 >> 23);
  LODWORD(v27) = v27 + v79 + (v44 & HIDWORD(v27) | v45 & (v44 | HIDWORD(v27))) + 1518500249;
  v47 = ((_DWORD)v27 << 13) | ((unsigned int)v27 >> 19);
  v48 = v44 + v64 + (v47 ^ HIDWORD(v27) ^ v45) + 1859775393;
  LODWORD(v27) = (8 * v48) | (v48 >> 29);
  v49 = v45 + v72 + (v27 ^ v47 ^ HIDWORD(v27)) + 1859775393;
  v50 = (v49 << 9) | (v49 >> 23);
  HIDWORD(v27) += v68 + (v27 ^ v47 ^ v50) + 1859775393;
  v51 = (HIDWORD(v27) << 11) | (HIDWORD(v27) >> 21);
  v52 = ((v47 + v76 + ((unsigned int)v27 ^ v51 ^ v50) + 1859775393) << 15) | ((v47
                                                                             + v76
                                                                             + ((unsigned int)v27 ^ v51 ^ v50)
                                                                             + 1859775393) >> 17);
  LODWORD(v27) = (8 * (v27 + v66 + (v52 ^ v51 ^ v50) + 1859775393)) | (((unsigned int)v27
                                                                      + v66
                                                                      + (v52 ^ v51 ^ v50)
                                                                      + 1859775393) >> 29);
  v53 = v50 + v74 + (v27 ^ v52 ^ v51) + 1859775393;
  HIDWORD(v27) = (v53 << 9) | (v53 >> 23);
  v54 = v51 + v70 + (v27 ^ v52 ^ HIDWORD(v27)) + 1859775393;
  v55 = (v54 << 11) | (v54 >> 21);
  v56 = ((v52 + v78 + ((unsigned int)v27 ^ v55 ^ HIDWORD(v27)) + 1859775393) << 15) | ((v52
                                                                                      + v78
                                                                                      + ((unsigned int)v27 ^ v55 ^ HIDWORD(v27))
                                                                                      + 1859775393) >> 17);
  LODWORD(v27) = (8 * (v27 + v65 + (v56 ^ v55 ^ HIDWORD(v27)) + 1859775393)) | (((unsigned int)v27
                                                                               + v65
                                                                               + (v56 ^ v55 ^ HIDWORD(v27))
                                                                               + 1859775393) >> 29);
  HIDWORD(v27) += v73 + (v27 ^ v56 ^ v55) + 1859775393;
  v57 = (HIDWORD(v27) << 9) | (HIDWORD(v27) >> 23);
  HIDWORD(v27) = v55 + v69 + (v27 ^ v56 ^ v57) + 1859775393;
  v58 = (HIDWORD(v27) << 11) | (HIDWORD(v27) >> 21);
  v59 = ((v56 + v77 + ((unsigned int)v27 ^ v58 ^ v57) + 1859775393) << 15) | ((v56
                                                                             + v77
                                                                             + ((unsigned int)v27 ^ v58 ^ v57)
                                                                             + 1859775393) >> 17);
  LODWORD(v27) = (8 * (v27 + v67 + (v59 ^ v58 ^ v57) + 1859775393)) | (((unsigned int)v27
                                                                      + v67
                                                                      + (v59 ^ v58 ^ v57)
                                                                      + 1859775393) >> 29);
  HIDWORD(v27) = v57 + v75 + (v27 ^ v59 ^ v58) + 1859775393;
  v60 = (HIDWORD(v27) << 9) | (HIDWORD(v27) >> 23);
  HIDWORD(v27) = v58 + v71 + (v27 ^ v59 ^ v60) + 1859775393;
  v61 = (HIDWORD(v27) << 11) | (HIDWORD(v27) >> 21);
  v62 = v59 + v79 + (v27 ^ v61 ^ v60) + 1859775393;
  *a1 += v27;
  HIDWORD(v27) = ((v62 << 15) | (v62 >> 17)) + a1[1];
  LODWORD(v27) = v61 + a1[2];
  result = v60 + a1[3];
  a1[1] = HIDWORD(v27);
  a1[2] = v27;
  a1[3] = result;
  return result;
}

//----- (00000810) --------------------------------------------------------
void __cdecl Encode(int a1, _BYTE *a2, unsigned int a3)
{
  _BYTE *v4; // eax
  char v5; // dl

  if ( a3 )
  {
    v4 = (_BYTE *)(a1 + 1);
    do
    {
      v5 = *a2;
      a2 += 4;
      *(v4 - 1) = v5;
      *v4 = BYTE1(*((_DWORD *)a2 - 1));
      v4[1] = BYTE2(*((_DWORD *)a2 - 1));
      v4[2] = HIBYTE(*((_DWORD *)a2 - 1));
      v4 += 4;
    }
    while ( (unsigned int)&v4[-1 - a1] < a3 );
  }
}

//----- (00000860) --------------------------------------------------------
void __cdecl Decode(int a1, int a2, unsigned int a3)
{
  unsigned __int16 *v4; // eax
  unsigned __int16 v5; // cx
  int v6; // edx

  if ( a3 )
  {
    v4 = (unsigned __int16 *)(a2 + 2);
    do
    {
      v5 = *v4;
      v6 = *((unsigned __int8 *)v4 - 1);
      v4 += 2;
      a1 += 4;
      *(_DWORD *)(a1 - 4) = *((unsigned __int8 *)v4 - 6) | ((v6 | (v5 << 8)) << 8);
    }
    while ( (unsigned int)v4 - 2 - a2 < a3 );
  }
}

// nfuncs=6 queued=6 decompiled=6 lumina nreq=0 worse=0 better=0
// ALL OK, 6 function(s) have been successfully decompiled
