/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

_DWORD *__cdecl opiemd5init(_DWORD *a1);
unsigned int __cdecl opiemd5update(int a1, char *a2, unsigned int a3);
int __cdecl opiemd5final(int a1, _DWORD *a2);
void __cdecl EEncode(int a1, _BYTE *a2, unsigned int a3);
int __cdecl MD5Transform(int *a1, int a2);
void __cdecl EDecode(int a1, int a2, unsigned int a3);

//-------------------------------------------------------------------------
// Data declarations

char PADDING[64] =
{
  '\x80',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0'
}; // idb


//----- (00000040) --------------------------------------------------------
_DWORD *__cdecl opiemd5init(_DWORD *a1)
{
  _DWORD *result; // eax

  result = a1;
  a1[5] = 0;
  a1[4] = 0;
  *a1 = 1732584193;
  a1[1] = -271733879;
  a1[2] = -1732584194;
  a1[3] = 271733878;
  return result;
}

//----- (00000070) --------------------------------------------------------
unsigned int __cdecl opiemd5update(int a1, char *a2, unsigned int a3)
{
  unsigned int v3; // ecx
  unsigned int v4; // edx
  int v5; // eax
  unsigned int v6; // ebp
  unsigned int v7; // edi
  unsigned int i; // esi
  unsigned int v9; // ecx
  char *v10; // esi
  char *v11; // edi
  unsigned int result; // eax

  v3 = a3;
  v4 = *(_DWORD *)(a1 + 16) + 8 * a3;
  v5 = (*(_DWORD *)(a1 + 16) >> 3) & 0x3F;
  *(_DWORD *)(a1 + 16) = v4;
  if ( v4 < 8 * a3 )
    ++*(_DWORD *)(a1 + 20);
  v6 = 64 - v5;
  *(_DWORD *)(a1 + 20) += a3 >> 29;
  if ( a3 < 64 - v5 )
  {
    v7 = 0;
  }
  else
  {
    qmemcpy((void *)(v5 + a1 + 24), a2, v6);
    MD5Transform((int *)a1, a1 + 24);
    v7 = v6;
    for ( i = v6 + 63; i < a3; v7 += 64 )
    {
      MD5Transform((int *)a1, (int)&a2[i - 63]);
      i += 64;
    }
    v3 = a3;
    v5 = 0;
  }
  v9 = v3 - v7;
  v10 = &a2[v7];
  v11 = (char *)(v5 + a1 + 24);
  result = v9;
  qmemcpy(v11, v10, v9);
  return result;
}

//----- (00000130) --------------------------------------------------------
int __cdecl opiemd5final(int a1, _DWORD *a2)
{
  unsigned int v2; // eax
  int v3; // ecx
  int result; // eax
  char v5[8]; // [esp+8h] [ebp-8h] BYREF

  EEncode((int)v5, (_BYTE *)a2 + 16, 8u);
  v2 = (a2[4] >> 3) & 0x3F;
  v3 = 56;
  if ( v2 >= 0x38 )
    v3 = 120;
  opiemd5update((int)a2, PADDING, v3 - v2);
  opiemd5update((int)a2, v5, 8u);
  EEncode(a1, a2, 0x10u);
  result = 0;
  memset(a2, 0, 0x58u);
  return result;
}

//----- (000001A0) --------------------------------------------------------
void __cdecl EEncode(int a1, _BYTE *a2, unsigned int a3)
{
  _BYTE *v4; // eax
  char v5; // dl

  if ( a3 )
  {
    v4 = (_BYTE *)(a1 + 1);
    do
    {
      v5 = *a2;
      a2 += 4;
      *(v4 - 1) = v5;
      *v4 = BYTE1(*((_DWORD *)a2 - 1));
      v4[1] = BYTE2(*((_DWORD *)a2 - 1));
      v4[2] = HIBYTE(*((_DWORD *)a2 - 1));
      v4 += 4;
    }
    while ( (unsigned int)&v4[-1 - a1] < a3 );
  }
}

//----- (000001F0) --------------------------------------------------------
int __cdecl MD5Transform(int *a1, int a2)
{
  int v3; // edi
  int v4; // ebx
  int v5; // ebp
  unsigned __int64 v6; // kr00_8
  int v7; // eax
  unsigned __int64 v8; // kr08_8
  int v9; // ecx
  unsigned int v10; // ebx
  int v11; // edx
  int v12; // edi
  unsigned int v13; // ecx
  int v14; // eax
  unsigned int v15; // edx
  int v16; // ecx
  unsigned int v17; // edi
  int v18; // edx
  unsigned int v19; // eax
  int v20; // edi
  unsigned int v21; // ecx
  int v22; // eax
  unsigned int v23; // edx
  int v24; // ecx
  unsigned int v25; // edi
  int v26; // edx
  unsigned int v27; // eax
  int v28; // edi
  unsigned int v29; // ecx
  int v30; // eax
  unsigned int v31; // edx
  int v32; // ecx
  unsigned int v33; // edi
  int v34; // edx
  unsigned int v35; // eax
  int v36; // edi
  unsigned int v37; // ecx
  int v38; // eax
  unsigned int v39; // edx
  int v40; // ecx
  unsigned int v41; // edi
  int v42; // edx
  unsigned int v43; // eax
  int v44; // edi
  unsigned int v45; // ecx
  int v46; // eax
  unsigned int v47; // edx
  int v48; // ecx
  unsigned int v49; // edi
  int v50; // edx
  unsigned int v51; // eax
  unsigned int v52; // edi
  unsigned int v53; // eax
  unsigned int v54; // ecx
  unsigned int v55; // ebx
  unsigned int v56; // edx
  unsigned int v57; // edi
  unsigned int v58; // eax
  unsigned int v59; // ecx
  unsigned int v60; // ebx
  unsigned int v61; // eax
  unsigned int v62; // edx
  unsigned int v63; // ebx
  unsigned int v64; // edi
  unsigned int v65; // edx
  unsigned int v66; // ecx
  unsigned int v67; // eax
  unsigned int v68; // ebx
  unsigned int v69; // edi
  unsigned int v70; // edx
  unsigned int v71; // ebx
  unsigned int v72; // ecx
  unsigned int v73; // eax
  unsigned int v74; // edi
  unsigned int v75; // edx
  unsigned int v76; // ebx
  unsigned int v77; // edi
  unsigned int v78; // ecx
  unsigned int v79; // ebx
  unsigned int v80; // eax
  unsigned int v81; // ecx
  unsigned int v82; // edx
  int v83; // eax
  unsigned int v84; // edi
  int v85; // edx
  unsigned int v86; // ebx
  int v87; // edi
  unsigned int v88; // ecx
  int v89; // ebx
  unsigned int v90; // eax
  int v91; // ecx
  unsigned int v92; // edx
  int v93; // eax
  unsigned int v94; // edi
  int v95; // edx
  unsigned int v96; // ebx
  int v97; // edi
  unsigned int v98; // ecx
  int v99; // ebx
  unsigned int v100; // eax
  int v101; // ecx
  unsigned int v102; // edx
  int v103; // eax
  unsigned int v104; // edi
  int v105; // edx
  unsigned int v106; // ebx
  int v107; // edi
  unsigned int v108; // ecx
  int v109; // ebx
  unsigned int v110; // eax
  int v111; // ecx
  int v112; // ebp
  int v113; // edx
  int v114; // eax
  int result; // eax
  int v116; // [esp+10h] [ebp-40h] BYREF
  int v117; // [esp+14h] [ebp-3Ch]
  int v118; // [esp+18h] [ebp-38h]
  int v119; // [esp+1Ch] [ebp-34h]
  int v120; // [esp+20h] [ebp-30h]
  int v121; // [esp+24h] [ebp-2Ch]
  int v122; // [esp+28h] [ebp-28h]
  int v123; // [esp+2Ch] [ebp-24h]
  int v124; // [esp+30h] [ebp-20h]
  int v125; // [esp+34h] [ebp-1Ch]
  int v126; // [esp+38h] [ebp-18h]
  int v127; // [esp+3Ch] [ebp-14h]
  int v128; // [esp+40h] [ebp-10h]
  int v129; // [esp+44h] [ebp-Ch]
  int v130; // [esp+48h] [ebp-8h]
  int v131; // [esp+4Ch] [ebp-4h]
  int v132; // [esp+54h] [ebp+4h]
  int v133; // [esp+54h] [ebp+4h]
  int v134; // [esp+54h] [ebp+4h]
  int v135; // [esp+54h] [ebp+4h]
  int v136; // [esp+54h] [ebp+4h]
  int v137; // [esp+54h] [ebp+4h]
  int v138; // [esp+54h] [ebp+4h]
  int v139; // [esp+54h] [ebp+4h]

  v3 = a1[1];
  v4 = a1[2];
  v5 = a1[3];
  v132 = *a1;
  EDecode((int)&v116, a2, 0x40u);
  v6 = (unsigned __int64)(v132 + v116 + (v3 & v4 | v5 & (unsigned int)~v3) - 680876936) << 7;
  v7 = v3 + (v6 | HIDWORD(v6));
  v8 = (unsigned __int64)(v117 + (v7 & v3 | v4 & (unsigned int)~v7) + v5 - 389564586) << 12;
  v9 = v7 + (v8 | HIDWORD(v8));
  v10 = v4 + v118 + (v7 & v9 | v3 & ~v9) + 606105819;
  v11 = v9 + ((v10 << 17) | (v10 >> 15));
  v133 = v11
       + (((v3 + v119 + (v11 & v9 | v7 & (unsigned int)~v11) - 1044525330) >> 10) | ((v3
                                                                                    + v119
                                                                                    + (v11 & v9 | v7 & ~v11)
                                                                                    - 1044525330) << 22));
  v12 = v133
      + (((v7 + v120 + (v133 & v11 | v9 & ~v133) - 176418897) << 7) | ((v7
                                                                      + v120
                                                                      + (v133 & v11 | v9 & (unsigned int)~v133)
                                                                      - 176418897) >> 25));
  v13 = v9 + v121 + (v12 & v133 | v11 & ~v12) + 1200080426;
  v14 = v12 + ((v13 << 12) | (v13 >> 20));
  v15 = v11 + v122 + (v12 & v14 | v133 & ~v14) - 1473231341;
  v16 = v14 + ((v15 << 17) | (v15 >> 15));
  v134 = v16
       + (((v133 + v123 + (v16 & v14 | v12 & (unsigned int)~v16) - 45705983) >> 10) | ((v133
                                                                                      + v123
                                                                                      + (v16 & v14 | v12 & ~v16)
                                                                                      - 45705983) << 22));
  v17 = v12 + v124 + (v134 & v16 | v14 & ~v134) + 1770035416;
  v18 = v134 + ((v17 << 7) | (v17 >> 25));
  v19 = v14 + v125 + (v18 & v134 | v16 & ~v18) - 1958414417;
  v20 = v18 + ((v19 << 12) | (v19 >> 20));
  v21 = v16 + v126 + (v18 & v20 | v134 & ~v20) - 42063;
  v22 = v20 + ((v21 << 17) | (v21 >> 15));
  v135 = v22
       + (((v134 + v127 + (v22 & v20 | v18 & (unsigned int)~v22) - 1990404162) >> 10) | ((v134
                                                                                        + v127
                                                                                        + (v22 & v20 | v18 & ~v22)
                                                                                        - 1990404162) << 22));
  v23 = v18 + v128 + (v135 & v22 | v20 & ~v135) + 1804603682;
  v24 = v135 + ((v23 << 7) | (v23 >> 25));
  v25 = v20 + v129 + (v24 & v135 | v22 & ~v24) - 40341101;
  v26 = v24 + ((v25 << 12) | (v25 >> 20));
  v27 = v22 + v130 + (~v26 & v135 | v24 & v26) - 1502002290;
  v28 = v26 + ((v27 << 17) | (v27 >> 15));
  v136 = v28
       + (((v135 + v131 + (v28 & v26 | v24 & (unsigned int)~v28) + 1236535329) >> 10) | ((v135
                                                                                        + v131
                                                                                        + (v28 & v26 | v24 & ~v28)
                                                                                        + 1236535329) << 22));
  v29 = v24 + v117 + (~v26 & v28 | v136 & v26) - 165796510;
  v30 = v136 + ((32 * v29) | (v29 >> 27));
  v31 = v26 + v122 + (v30 & v28 | v136 & ~v28) - 1069501632;
  v32 = v30 + ((v31 << 9) | (v31 >> 23));
  v33 = v28 + v127 + (v136 & v32 | v30 & ~v136) + 643717713;
  v34 = v32 + ((v33 << 14) | (v33 >> 18));
  v137 = v34
       + (((v136 + v116 + (v30 & v34 | v32 & (unsigned int)~v30) - 373897302) >> 12) | ((v136
                                                                                       + v116
                                                                                       + (v30 & v34 | v32 & ~v30)
                                                                                       - 373897302) << 20));
  v35 = v30 + v121 + (v137 & v32 | v34 & ~v32) - 701558691;
  v36 = v137 + ((32 * v35) | (v35 >> 27));
  v37 = v32 + v126 + (v36 & v34 | v137 & ~v34) + 38016083;
  v38 = v36 + ((v37 << 9) | (v37 >> 23));
  v39 = v34 + v131 + (v137 & v38 | v36 & ~v137) - 660478335;
  v40 = v38 + ((v39 << 14) | (v39 >> 18));
  v138 = v40
       + (((v137 + v120 + (v36 & v40 | v38 & (unsigned int)~v36) - 405537848) >> 12) | ((v137
                                                                                       + v120
                                                                                       + (v36 & v40 | v38 & ~v36)
                                                                                       - 405537848) << 20));
  v41 = v36 + v125 + (v138 & v38 | v40 & ~v38) + 568446438;
  v42 = v138 + ((32 * v41) | (v41 >> 27));
  v43 = v38 + v130 + (v42 & v40 | v138 & ~v40) - 1019803690;
  v44 = v42 + ((v43 << 9) | (v43 >> 23));
  v45 = v40 + v119 + (v138 & v44 | v42 & ~v138) - 187363961;
  v46 = v44 + ((v45 << 14) | (v45 >> 18));
  v139 = v46
       + (((v138 + v124 + (v42 & v46 | v44 & (unsigned int)~v42) + 1163531501) >> 12) | ((v138
                                                                                        + v124
                                                                                        + (v42 & v46 | v44 & ~v42)
                                                                                        + 1163531501) << 20));
  v47 = v42 + v129 + (v139 & v44 | v46 & ~v44) - 1444681467;
  v48 = v139 + ((32 * v47) | (v47 >> 27));
  v49 = v44 + v118 + (v48 & v46 | v139 & ~v46) - 51403784;
  v50 = v48 + ((v49 << 9) | (v49 >> 23));
  v51 = v46 + v123 + (v139 & v50 | v48 & ~v139) + 1735328473;
  v52 = v50 + ((v51 << 14) | (v51 >> 18));
  v53 = v52
      + (((v139 + v128 + (v48 & v52 | v50 & ~v48) - 1926607734) >> 12) | ((v139
                                                                         + v128
                                                                         + (v48 & v52 | v50 & ~v48)
                                                                         - 1926607734) << 20));
  v54 = v48 + v121 + (v53 ^ v52 ^ v50) - 378558;
  v55 = v53 + ((16 * v54) | (v54 >> 28));
  v56 = v55
      + (((v50 + v124 + (v55 ^ v53 ^ v52) - 2022574463) << 11) | ((v50 + v124 + (v55 ^ v53 ^ v52) - 2022574463) >> 21));
  v57 = v56
      + (((v52 + v127 + (v55 ^ v53 ^ v56) + 1839030562) << 16) | ((v52 + v127 + (v55 ^ v53 ^ v56) + 1839030562) >> 16));
  v58 = v53 + v130 + (v55 ^ v57 ^ v56) - 35309556;
  v59 = v57 + ((v58 >> 9) | (v58 << 23));
  v60 = v55 + v117 + (v59 ^ v57 ^ v56) - 1530992060;
  v61 = v59 + ((16 * v60) | (v60 >> 28));
  v62 = v56 + v120 + (v61 ^ v59 ^ v57) + 1272893353;
  v63 = v61 + ((v62 << 11) | (v62 >> 21));
  v64 = v57 + v123 + (v61 ^ v59 ^ v63) - 155497632;
  v65 = v63 + ((v64 << 16) | HIWORD(v64));
  v66 = v65
      + (((v59 + v126 + (v61 ^ v65 ^ v63) - 1094730640) >> 9) | ((v59 + v126 + (v61 ^ v65 ^ v63) - 1094730640) << 23));
  v67 = v66
      + ((16 * (v61 + v129 + (v66 ^ v65 ^ v63) + 681279174)) | ((v61 + v129 + (v66 ^ v65 ^ v63) + 681279174) >> 28));
  v68 = v63 + v116 + (v67 ^ v66 ^ v65) - 358537222;
  v69 = v67 + ((v68 << 11) | (v68 >> 21));
  v70 = v65 + v119 + (v67 ^ v66 ^ v69) - 722521979;
  v71 = v69 + ((v70 << 16) | HIWORD(v70));
  v72 = v71 + (((v66 + v122 + (v67 ^ v71 ^ v69) + 76029189) >> 9) | ((v66 + v122 + (v67 ^ v71 ^ v69) + 76029189) << 23));
  v73 = v72
      + ((16 * (v67 + v125 + (v72 ^ v71 ^ v69) - 640364487)) | ((v67 + v125 + (v72 ^ v71 ^ v69) - 640364487) >> 28));
  v74 = v69 + v128 + (v73 ^ v72 ^ v71) - 421815835;
  v75 = v73 + ((v74 << 11) | (v74 >> 21));
  v76 = v71 + v131 + (v73 ^ v72 ^ v75) + 530742520;
  v77 = v75 + ((v76 << 16) | HIWORD(v76));
  v78 = v72 + v118 + (v73 ^ v77 ^ v75) - 995338651;
  v79 = v77 + ((v78 >> 9) | (v78 << 23));
  v80 = v73 + v116 + (v77 ^ (v79 | ~v75)) - 198630844;
  v81 = v79 + ((v80 << 6) | (v80 >> 26));
  v82 = v75 + v123 + (v79 ^ (v81 | ~v77)) + 1126891415;
  v83 = v81 + ((v82 << 10) | (v82 >> 22));
  v84 = v77 + v130 + (v81 ^ (v83 | ~v79)) - 1416354905;
  v85 = v83 + ((v84 << 15) | (v84 >> 17));
  v86 = v79 + v121 + (v83 ^ (v85 | ~v81)) - 57434055;
  v87 = v85 + ((v86 >> 11) | (v86 << 21));
  v88 = v81 + v128 + (v85 ^ (v87 | ~v83)) + 1700485571;
  v89 = v87 + ((v88 << 6) | (v88 >> 26));
  v90 = v83 + v119 + (v87 ^ (v89 | ~v85)) - 1894986606;
  v91 = v89 + ((v90 << 10) | (v90 >> 22));
  v92 = v85 + v126 + (v89 ^ (v91 | ~v87)) - 1051523;
  v93 = v91 + ((v92 << 15) | (v92 >> 17));
  v94 = v87 + v117 + (v91 ^ (v93 | ~v89)) - 2054922799;
  v95 = v93 + ((v94 >> 11) | (v94 << 21));
  v96 = v89 + v124 + (v93 ^ (v95 | ~v91)) + 1873313359;
  v97 = v95 + ((v96 << 6) | (v96 >> 26));
  v98 = v91 + v131 + (v95 ^ (v97 | ~v93)) - 30611744;
  v99 = v97 + ((v98 << 10) | (v98 >> 22));
  v100 = v93 + v122 + (v97 ^ (v99 | ~v95)) - 1560198380;
  v101 = v99 + ((v100 << 15) | (v100 >> 17));
  v102 = v95 + v129 + (v99 ^ (v101 | ~v97)) + 1309151649;
  v103 = v101 + ((v102 >> 11) | (v102 << 21));
  v104 = v97 + v120 + (v101 ^ (v103 | ~v99)) - 145523070;
  v105 = v103 + ((v104 << 6) | (v104 >> 26));
  v106 = v99 + v127 + (v103 ^ (v105 | ~v101)) - 1120210379;
  v107 = v105 + ((v106 << 10) | (v106 >> 22));
  v108 = v101 + v118 + (v105 ^ (v107 | ~v103)) + 718787259;
  v109 = v107 + ((v108 << 15) | (v108 >> 17));
  v110 = v103 + v125 + (v107 ^ (v109 | ~v105)) - 343485551;
  v111 = a1[2];
  *a1 += v105;
  v112 = a1[1];
  v113 = (v110 >> 11) | (v110 << 21);
  v114 = a1[3];
  a1[2] = v109 + v111;
  result = v107 + v114;
  a1[1] = v109 + v113 + v112;
  a1[3] = result;
  return result;
}
// 1F0: too many cbuild loops

//----- (00000B30) --------------------------------------------------------
void __cdecl EDecode(int a1, int a2, unsigned int a3)
{
  unsigned __int16 *v4; // eax
  unsigned __int16 v5; // cx
  int v6; // edx

  if ( a3 )
  {
    v4 = (unsigned __int16 *)(a2 + 2);
    do
    {
      v5 = *v4;
      v6 = *((unsigned __int8 *)v4 - 1);
      v4 += 2;
      a1 += 4;
      *(_DWORD *)(a1 - 4) = *((unsigned __int8 *)v4 - 6) | ((v6 | (v5 << 8)) << 8);
    }
    while ( (unsigned int)v4 - 2 - a2 < a3 );
  }
}

// nfuncs=6 queued=6 decompiled=6 lumina nreq=0 worse=0 better=0
// ALL OK, 6 function(s) have been successfully decompiled
