/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int __cdecl main(int argc, const char **argv, const char **envp);
int __cdecl do_fp(FILE *Stream); // idb
int __cdecl pt(int a1);
// void __cdecl __noreturn _exit(int Code);
// int __cdecl _fclose(FILE *Stream);
// void __cdecl _perror(const char *ErrMsg);
// int _printf(const char *const Format, ...);
// FILE *__cdecl _fopen(const char *FileName, const char *Mode);
// int __cdecl SHA_Final(_DWORD, _DWORD); weak
// int __cdecl SHA_Update(_DWORD, _DWORD, _DWORD); weak
// int __cdecl read(int FileHandle, void *DstBuf, unsigned int MaxCharCount);
// int __cdecl SHA_Init(_DWORD); weak
// int __cdecl _fileno(FILE *Stream);

//-------------------------------------------------------------------------
// Data declarations

// extern FILE __iob[];


//----- (00000000) --------------------------------------------------------
int __cdecl __noreturn main(int argc, const char **argv, const char **envp)
{
  FILE *(__cdecl *v3)(const char *, const char *); // ebx
  void (*v4)(const char *const, ...); // ebp
  const char **v5; // edi
  FILE *v6; // esi
  int Code; // [esp+0h] [ebp-4h]
  int argca; // [esp+8h] [ebp+4h]

  Code = 0;
  if ( argc == 1 )
  {
    do_fp((FILE *)__iob[0]._ptr);
  }
  else if ( argc > 1 )
  {
    v3 = _fopen;
    v4 = (void (*)(const char *const, ...))_printf;
    v5 = argv + 1;
    argca = argc - 1;
    do
    {
      v6 = v3(*v5, "r");
      if ( v6 )
      {
        v4("SHA(%s)= ", *v5);
        do_fp(v6);
        _fclose(v6);
      }
      else
      {
        _perror(*v5);
        ++Code;
      }
      ++v5;
      --argca;
    }
    while ( argca );
  }
  _exit(Code);
}

//----- (000000C0) --------------------------------------------------------
int __cdecl do_fp(FILE *Stream)
{
  int v1; // esi
  int i; // eax
  char v4[20]; // [esp+4h] [ebp-4074h] BYREF
  char v5[96]; // [esp+18h] [ebp-4060h] BYREF
  char DstBuf[16384]; // [esp+78h] [ebp-4000h] BYREF

  v1 = _fileno(Stream);
  SHA_Init(v5);
  for ( i = read(v1, DstBuf, 0x4000u); i > 0; i = read(v1, DstBuf, 0x4000u) )
    SHA_Update(v5, DstBuf, i);
  SHA_Final(v4, v5);
  return pt((int)v4);
}
// 1B8: using guessed type int __cdecl SHA_Final(_DWORD, _DWORD);
// 1BC: using guessed type int __cdecl SHA_Update(_DWORD, _DWORD, _DWORD);
// 1C4: using guessed type int __cdecl SHA_Init(_DWORD);

//----- (00000150) --------------------------------------------------------
int __cdecl pt(int a1)
{
  void (*v1)(const char *const, ...); // edi
  int i; // esi

  v1 = (void (*)(const char *const, ...))_printf;
  for ( i = 0; i < 20; ++i )
    v1("%02x", *(unsigned __int8 *)(i + a1));
  return ((int (*)(const char *const, ...))v1)("\n");
}

// nfuncs=14 queued=3 decompiled=3 lumina nreq=0 worse=0 better=0
// ALL OK, 3 function(s) have been successfully decompiled
