/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

_DWORD *__cdecl SHA1_Init(_DWORD *a1);
void __cdecl SHA1_Update(_DWORD *a1, unsigned __int8 *a2, unsigned int a3);
_DWORD *__cdecl SHA1_Transform(_DWORD *a1, unsigned __int8 *a2);
_DWORD *__cdecl sha1_block(_DWORD *a1, _DWORD *a2, int a3);
_BYTE *__cdecl SHA1_Final(_BYTE *a1, int *a2);

//-------------------------------------------------------------------------
// Data declarations

int _end__1__SHA1_Final__9_9 = 128; // weak


//----- (00000030) --------------------------------------------------------
_DWORD *__cdecl SHA1_Init(_DWORD *a1)
{
  _DWORD *result; // eax

  result = a1;
  *a1 = 1732584193;
  a1[1] = -271733879;
  a1[2] = -1732584194;
  a1[3] = 271733878;
  a1[4] = -1009589776;
  a1[5] = 0;
  a1[6] = 0;
  a1[23] = 0;
  return result;
}

//----- (00000070) --------------------------------------------------------
void __cdecl SHA1_Update(_DWORD *a1, unsigned __int8 *a2, unsigned int a3)
{
  int v3; // ebx
  unsigned int v4; // ecx
  unsigned int v5; // eax
  int v6; // edx
  int v7; // eax
  int v8; // edi
  char v9; // cl
  int v10; // eax
  _DWORD *v11; // edx
  int v12; // edi
  int v13; // ecx
  int v14; // eax
  unsigned __int16 v15; // cx
  unsigned __int8 *v16; // esi
  unsigned __int16 v17; // cx
  unsigned __int16 v18; // cx
  int v19; // edi
  _DWORD *v20; // ecx
  int v21; // eax
  _BYTE *v22; // esi
  unsigned __int16 v23; // dx
  int v24; // eax
  int v25; // edx
  int v26; // esi
  int v27; // ecx
  unsigned __int8 *v28; // ebp
  _BYTE *v29; // ebp
  unsigned __int16 v30; // cx
  unsigned __int16 v31; // cx
  int v32; // ebp
  int v33; // esi
  int v34; // ebx
  unsigned __int16 v35; // cx
  unsigned __int8 *v36; // eax
  unsigned __int16 v37; // cx
  unsigned __int16 v38; // cx
  int v39; // edi
  int v40; // esi
  _DWORD *v41; // ebp
  int v42; // ecx
  unsigned __int8 *v43; // eax
  unsigned __int16 v44; // bx
  int v45; // ecx
  int v46; // esi
  unsigned __int8 *v47; // eax
  unsigned __int16 v48; // cx
  _DWORD *v49; // edi
  int v50; // ecx
  int v51; // eax
  unsigned __int8 *v52; // esi
  unsigned __int16 v53; // dx
  int v54; // eax
  int v55; // eax
  int v56; // eax
  int v57; // eax
  int v58; // eax
  int v59; // eax
  int v60; // eax
  int v61; // eax
  int v62; // ebx
  int v63; // edx
  _DWORD *v64; // ecx
  int v65; // ebp
  int v66; // eax
  unsigned __int8 *v67; // esi
  unsigned __int16 v68; // dx
  int v69; // eax
  int v70; // eax
  unsigned __int8 *v71; // esi
  int v72; // [esp+18h] [ebp+8h]
  unsigned int v73; // [esp+18h] [ebp+8h]
  int v74; // [esp+18h] [ebp+8h]
  int v75; // [esp+1Ch] [ebp+Ch]

  v3 = a3;
  if ( a3 )
  {
    v4 = a1[5];
    v5 = v4 + 8 * a3;
    if ( v5 < v4 )
      ++a1[6];
    v6 = a1[6];
    a1[5] = v5;
    v7 = a1[23];
    a1[6] = (a3 >> 29) + v6;
    if ( !v7 )
    {
      v16 = a2;
      goto LABEL_46;
    }
    v8 = v7;
    v9 = v7;
    v10 = a3 + v7;
    v11 = a1 + 7;
    v12 = v8 >> 2;
    v13 = v9 & 3;
    if ( (unsigned int)v10 >= 0x40 )
    {
      v14 = v11[v12];
      switch ( v13 )
      {
        case 0:
          LOBYTE(v15) = 0;
          HIBYTE(v15) = a2[2];
          v14 = a2[3] | v15 | (a2[1] << 16) | (*a2 << 24);
          v16 = a2 + 4;
          break;
        case 1:
          LOBYTE(v17) = 0;
          HIBYTE(v17) = a2[1];
          v14 |= a2[2] | v17 | (*a2 << 16);
          v16 = a2 + 3;
          break;
        case 2:
          LOBYTE(v18) = 0;
          HIBYTE(v18) = *a2;
          v14 |= a2[1] | v18;
          v16 = a2 + 2;
          break;
        case 3:
          v14 |= *a2;
          v16 = a2 + 1;
          break;
        default:
          v16 = a2;
          break;
      }
      v11[v12] = v14;
      v19 = v12 + 1;
      if ( v19 < 16 )
      {
        v20 = &v11[v19];
        v72 = 16 - v19;
        do
        {
          ++v20;
          v21 = (v16[1] << 16) | (*v16 << 24);
          v22 = v16 + 2;
          LOBYTE(v23) = 0;
          HIBYTE(v23) = *v22;
          v24 = v23 | v21;
          v25 = (unsigned __int8)*++v22;
          v16 = v22 + 1;
          *(v20 - 1) = v25 | v24;
          --v72;
        }
        while ( v72 );
        v11 = a1 + 7;
      }
      v3 = a3 + a1[23] - 64;
      sha1_block(a1, v11, 64);
      a1[23] = 0;
LABEL_46:
      v49 = a1 + 7;
      if ( (unsigned int)v3 >= 0x40 )
      {
        v73 = (unsigned int)v3 >> 6;
        do
        {
          v50 = 4;
          do
          {
            v51 = (v16[1] << 16) | (*v16 << 24);
            v52 = v16 + 2;
            LOBYTE(v53) = 0;
            HIBYTE(v53) = *v52++;
            v49 += 4;
            v54 = *v52++ | v53 | v51;
            *(v49 - 4) = v54;
            v55 = (v52[1] << 16) | (*v52 << 24);
            v52 += 2;
            LOBYTE(v53) = 0;
            HIBYTE(v53) = *v52++;
            v56 = *v52++ | v53 | v55;
            *(v49 - 3) = v56;
            v57 = (v52[1] << 16) | (*v52 << 24);
            v52 += 2;
            LOBYTE(v53) = 0;
            HIBYTE(v53) = *v52++;
            v58 = *v52++ | v53 | v57;
            *(v49 - 2) = v58;
            v59 = (v52[1] << 16) | (*v52 << 24);
            v52 += 2;
            LOBYTE(v53) = 0;
            HIBYTE(v53) = *v52++;
            v60 = *v52 | v53 | v59;
            v16 = v52 + 1;
            *(v49 - 1) = v60;
            --v50;
          }
          while ( v50 );
          v49 = a1 + 7;
          sha1_block(a1, a1 + 7, 64);
          v3 -= 64;
          --v73;
        }
        while ( v73 );
      }
      a1[23] = v3;
      v61 = v3 >> 2;
      v62 = v3 & 3;
      v63 = 0;
      if ( v61 > 0 )
      {
        v64 = v49;
        v65 = v61;
        v74 = v61;
        do
        {
          ++v64;
          v66 = (v16[1] << 16) | (*v16 << 24);
          v67 = v16 + 2;
          LOBYTE(v68) = 0;
          HIBYTE(v68) = *v67++;
          v69 = *v67 | v68 | v66;
          v16 = v67 + 1;
          *(v64 - 1) = v69;
          --v65;
        }
        while ( v65 );
        v63 = v74;
      }
      v70 = 0;
      v71 = &v16[v62];
      if ( v62 != 1 )
      {
        if ( v62 != 2 )
        {
          if ( v62 != 3 )
          {
LABEL_61:
            v49[v63] = v70;
            return;
          }
          BYTE1(v70) = *--v71;
        }
        v70 |= *--v71 << 16;
      }
      v70 |= *(v71 - 1) << 24;
      goto LABEL_61;
    }
    a1[23] = v10;
    if ( v13 + a3 < 4 )
    {
      v26 = v11[v12];
      if ( v13 )
      {
        v27 = v13 - 1;
        if ( v27 )
        {
          if ( v27 != 1 )
          {
            v11[v12] = v26;
            return;
          }
          LOBYTE(v31) = 0;
          HIBYTE(v31) = *a2;
          v26 |= v31;
          goto LABEL_28;
        }
        v28 = a2;
      }
      else
      {
        v26 = *a2 << 24;
        v28 = a2 + 1;
        v3 = a3 - 1;
        if ( a3 == 1 )
        {
LABEL_28:
          v11[v12] = v26;
          return;
        }
      }
      v26 |= *v28 << 16;
      v29 = v28 + 1;
      if ( v3 != 1 )
      {
        LOBYTE(v30) = 0;
        HIBYTE(v30) = *v29;
        v11[v12] = v30 | v26;
        return;
      }
      goto LABEL_28;
    }
    v32 = v11[v12];
    v33 = v10 >> 2;
    v34 = v10 & 3;
    v75 = v34;
    switch ( v13 )
    {
      case 0:
        LOBYTE(v35) = 0;
        HIBYTE(v35) = a2[2];
        v32 = a2[3] | v35 | (a2[1] << 16) | (*a2 << 24);
        v36 = a2 + 4;
        break;
      case 1:
        LOBYTE(v37) = 0;
        HIBYTE(v37) = a2[1];
        v32 |= a2[2] | v37 | (*a2 << 16);
        v36 = a2 + 3;
        break;
      case 2:
        LOBYTE(v38) = 0;
        HIBYTE(v38) = *a2;
        v32 |= a2[1] | v38;
        v36 = a2 + 2;
        break;
      case 3:
        v32 |= *a2;
        v36 = a2 + 1;
        break;
      default:
        v36 = a2;
        break;
    }
    v11[v12] = v32;
    v39 = v12 + 1;
    if ( v39 < v33 )
    {
      v40 = v33 - v39;
      v41 = &v11[v39];
      v39 += v40;
      do
      {
        ++v41;
        v42 = (v36[1] << 16) | (*v36 << 24);
        v43 = v36 + 2;
        LOBYTE(v44) = 0;
        HIBYTE(v44) = *v43++;
        v45 = *v43 | v44 | v42;
        v36 = v43 + 1;
        *(v41 - 1) = v45;
        --v40;
      }
      while ( v40 );
      v34 = v75;
    }
    if ( v34 )
    {
      v46 = 0;
      v47 = &v36[v34];
      if ( v34 != 1 )
      {
        if ( v34 != 2 )
        {
          --v47;
          LOBYTE(v48) = 0;
          HIBYTE(v48) = *v47;
          v46 = v48;
        }
        v46 |= *--v47 << 16;
      }
      v11[v39] = (*(v47 - 1) << 24) | v46;
    }
  }
}
// 2F3: conditional instruction was optimized away because of 'ebx.4==3'

//----- (00000490) --------------------------------------------------------
_DWORD *__cdecl SHA1_Transform(_DWORD *a1, unsigned __int8 *a2)
{
  _DWORD *v3; // ecx
  int v4; // edi
  int v5; // esi
  unsigned __int8 *v6; // eax
  unsigned __int16 v7; // dx
  int v8; // esi
  int v9; // esi
  int v10; // esi
  int v11; // esi
  int v12; // esi
  int v13; // esi
  int v14; // esi
  _DWORD v16[16]; // [esp+8h] [ebp-40h] BYREF

  v3 = v16;
  v4 = 4;
  do
  {
    v3 += 4;
    v5 = (a2[1] << 16) | (*a2 << 24);
    v6 = a2 + 2;
    LOBYTE(v7) = 0;
    HIBYTE(v7) = *v6++;
    v8 = *v6++ | v7 | v5;
    *(v3 - 4) = v8;
    v9 = (v6[1] << 16) | (*v6 << 24);
    v6 += 2;
    LOBYTE(v7) = 0;
    HIBYTE(v7) = *v6++;
    v10 = *v6++ | v7 | v9;
    *(v3 - 3) = v10;
    v11 = (v6[1] << 16) | (*v6 << 24);
    v6 += 2;
    LOBYTE(v7) = 0;
    HIBYTE(v7) = *v6++;
    v12 = *v6++ | v7 | v11;
    *(v3 - 2) = v12;
    v13 = (v6[1] << 16) | (*v6 << 24);
    v6 += 2;
    LOBYTE(v7) = 0;
    HIBYTE(v7) = *v6++;
    v14 = *v6 | v7 | v13;
    a2 = v6 + 1;
    *(v3 - 1) = v14;
    --v4;
  }
  while ( v4 );
  return sha1_block(a1, v16, 64);
}

//----- (00000570) --------------------------------------------------------
_DWORD *__cdecl sha1_block(_DWORD *a1, _DWORD *a2, int a3)
{
  _DWORD *result; // eax
  int v4; // esi
  int v5; // edi
  int v6; // ebx
  int v7; // edx
  int v8; // esi
  int v9; // ebx
  int v10; // edx
  int v11; // edi
  int v12; // esi
  int v13; // edx
  int v14; // edi
  int v15; // esi
  int v16; // edx
  int v17; // edi
  int v18; // esi
  int v19; // edx
  int v20; // ebp
  int v21; // ebx
  int v22; // esi
  int v23; // ebx
  int v24; // ebx
  int v25; // ebx
  int v26; // ebx
  int v27; // edx
  int v28; // edi
  int v29; // ebp
  int v30; // edi
  int v31; // esi
  int v32; // ebx
  int v33; // esi
  int v34; // edi
  int v35; // ebx
  int v36; // ebx
  int v37; // ebx
  int v38; // ebx
  int v39; // edi
  int v40; // esi
  int v41; // esi
  int v42; // edi
  int v43; // edi
  int v44; // esi
  int v45; // edi
  int v46; // esi
  int v47; // ebp
  int v48; // edx
  int v49; // ebx
  int v50; // edx
  int v51; // esi
  int v52; // ebx
  int v53; // ebx
  int v54; // ebp
  int v55; // ebx
  int v56; // ebx
  int v57; // ebx
  int v58; // ebx
  int v59; // ebx
  int v60; // ebp
  int v61; // ebp
  int v62; // esi
  int v63; // ebx
  int v64; // ebp
  int v65; // edx
  int v66; // edi
  int v67; // ebp
  int v68; // ebx
  int v69; // edx
  int v70; // esi
  int v71; // edx
  int v72; // esi
  int v73; // edi
  int v74; // edx
  int v75; // esi
  int v76; // edi
  int v77; // edx
  int v78; // esi
  int v79; // edi
  int v80; // ebx
  int v81; // edx
  int v82; // esi
  int v83; // edi
  int v84; // ebx
  int v85; // ebx
  int v86; // ebx
  int v87; // ebx
  int v88; // ebx
  int v89; // ebx
  int v90; // edx
  int v91; // edi
  int v92; // ebp
  int v93; // esi
  int v94; // ebx
  int v95; // edi
  int v96; // edi
  int v97; // ebx
  int v98; // edi
  int v99; // ebx
  int v100; // esi
  int v101; // esi
  int v102; // edi
  int v103; // ebx
  int v104; // esi
  int v105; // edi
  int v106; // ebp
  int v107; // edx
  int v108; // ebx
  int v109; // edx
  int v110; // esi
  int v111; // ebx
  int v112; // ebx
  int v113; // ebp
  int v114; // ebx
  int v115; // ebx
  int v116; // ebx
  int v117; // ebx
  int v118; // ebx
  int v119; // ebx
  int v120; // ebp
  int v121; // ebp
  int v122; // esi
  int v123; // ebp
  int v124; // edi
  int v125; // [esp+10h] [ebp-94h]
  int v126; // [esp+10h] [ebp-94h]
  int v127; // [esp+10h] [ebp-94h]
  int v128; // [esp+10h] [ebp-94h]
  int v129; // [esp+10h] [ebp-94h]
  int v130; // [esp+10h] [ebp-94h]
  int v131; // [esp+10h] [ebp-94h]
  int v132; // [esp+10h] [ebp-94h]
  int v133; // [esp+10h] [ebp-94h]
  int v134; // [esp+10h] [ebp-94h]
  int v135; // [esp+10h] [ebp-94h]
  int v136; // [esp+10h] [ebp-94h]
  int v137; // [esp+10h] [ebp-94h]
  int v138; // [esp+10h] [ebp-94h]
  int v139; // [esp+10h] [ebp-94h]
  int v140; // [esp+10h] [ebp-94h]
  int v141; // [esp+10h] [ebp-94h]
  int v142; // [esp+10h] [ebp-94h]
  int v143; // [esp+10h] [ebp-94h]
  int v144; // [esp+10h] [ebp-94h]
  int v145; // [esp+10h] [ebp-94h]
  int v146; // [esp+10h] [ebp-94h]
  int v147; // [esp+10h] [ebp-94h]
  int v148; // [esp+10h] [ebp-94h]
  int v149; // [esp+10h] [ebp-94h]
  int v150; // [esp+10h] [ebp-94h]
  int v151; // [esp+10h] [ebp-94h]
  int v152; // [esp+10h] [ebp-94h]
  int v153; // [esp+10h] [ebp-94h]
  int v154; // [esp+10h] [ebp-94h]
  int v155; // [esp+10h] [ebp-94h]
  int v156; // [esp+10h] [ebp-94h]
  int v157; // [esp+10h] [ebp-94h]
  int v158; // [esp+10h] [ebp-94h]
  int v159; // [esp+10h] [ebp-94h]
  int v160; // [esp+10h] [ebp-94h]
  int v161; // [esp+10h] [ebp-94h]
  int v162; // [esp+10h] [ebp-94h]
  int v163; // [esp+10h] [ebp-94h]
  int v164; // [esp+10h] [ebp-94h]
  int v165; // [esp+10h] [ebp-94h]
  int v166; // [esp+10h] [ebp-94h]
  int v167; // [esp+10h] [ebp-94h]
  int v168; // [esp+10h] [ebp-94h]
  int v169; // [esp+10h] [ebp-94h]
  int v170; // [esp+10h] [ebp-94h]
  int v171; // [esp+14h] [ebp-90h]
  int v172; // [esp+14h] [ebp-90h]
  int v173; // [esp+14h] [ebp-90h]
  int v174; // [esp+14h] [ebp-90h]
  int v175; // [esp+14h] [ebp-90h]
  int v176; // [esp+14h] [ebp-90h]
  int v177; // [esp+14h] [ebp-90h]
  int v178; // [esp+14h] [ebp-90h]
  int v179; // [esp+14h] [ebp-90h]
  int v180; // [esp+14h] [ebp-90h]
  int v181; // [esp+14h] [ebp-90h]
  int v182; // [esp+14h] [ebp-90h]
  int v183; // [esp+14h] [ebp-90h]
  int v184; // [esp+14h] [ebp-90h]
  int v185; // [esp+14h] [ebp-90h]
  int v186; // [esp+14h] [ebp-90h]
  int v187; // [esp+14h] [ebp-90h]
  int v188; // [esp+14h] [ebp-90h]
  int v189; // [esp+14h] [ebp-90h]
  int v190; // [esp+14h] [ebp-90h]
  int v191; // [esp+14h] [ebp-90h]
  int v192; // [esp+14h] [ebp-90h]
  int v193; // [esp+14h] [ebp-90h]
  int v194; // [esp+14h] [ebp-90h]
  int v195; // [esp+14h] [ebp-90h]
  int v196; // [esp+14h] [ebp-90h]
  int v197; // [esp+14h] [ebp-90h]
  int v198; // [esp+14h] [ebp-90h]
  int v199; // [esp+14h] [ebp-90h]
  int v200; // [esp+14h] [ebp-90h]
  int v201; // [esp+14h] [ebp-90h]
  int v202; // [esp+14h] [ebp-90h]
  int v203; // [esp+14h] [ebp-90h]
  int v204; // [esp+14h] [ebp-90h]
  int v205; // [esp+14h] [ebp-90h]
  int v206; // [esp+14h] [ebp-90h]
  int v207; // [esp+14h] [ebp-90h]
  int v208; // [esp+14h] [ebp-90h]
  int v209; // [esp+18h] [ebp-8Ch]
  int v210; // [esp+18h] [ebp-8Ch]
  int v211; // [esp+18h] [ebp-8Ch]
  int v212; // [esp+18h] [ebp-8Ch]
  int v213; // [esp+18h] [ebp-8Ch]
  int v214; // [esp+18h] [ebp-8Ch]
  int v215; // [esp+18h] [ebp-8Ch]
  int v216; // [esp+18h] [ebp-8Ch]
  int v217; // [esp+18h] [ebp-8Ch]
  int v218; // [esp+18h] [ebp-8Ch]
  int v219; // [esp+18h] [ebp-8Ch]
  int v220; // [esp+18h] [ebp-8Ch]
  int v221; // [esp+18h] [ebp-8Ch]
  int v222; // [esp+18h] [ebp-8Ch]
  int v223; // [esp+18h] [ebp-8Ch]
  int v224; // [esp+18h] [ebp-8Ch]
  int v225; // [esp+18h] [ebp-8Ch]
  int v226; // [esp+18h] [ebp-8Ch]
  int v227; // [esp+18h] [ebp-8Ch]
  int v228; // [esp+18h] [ebp-8Ch]
  int v229; // [esp+18h] [ebp-8Ch]
  int v230; // [esp+18h] [ebp-8Ch]
  int v231; // [esp+18h] [ebp-8Ch]
  int v232; // [esp+18h] [ebp-8Ch]
  int v233; // [esp+18h] [ebp-8Ch]
  int v234; // [esp+18h] [ebp-8Ch]
  int v235; // [esp+18h] [ebp-8Ch]
  int v236; // [esp+18h] [ebp-8Ch]
  int v237; // [esp+18h] [ebp-8Ch]
  int v238; // [esp+18h] [ebp-8Ch]
  int v239; // [esp+18h] [ebp-8Ch]
  int v240; // [esp+18h] [ebp-8Ch]
  int v241; // [esp+18h] [ebp-8Ch]
  int v242; // [esp+18h] [ebp-8Ch]
  int v243; // [esp+18h] [ebp-8Ch]
  int v244; // [esp+18h] [ebp-8Ch]
  int v245; // [esp+18h] [ebp-8Ch]
  int v246; // [esp+18h] [ebp-8Ch]
  int v247; // [esp+1Ch] [ebp-88h]
  int v248; // [esp+1Ch] [ebp-88h]
  int v249; // [esp+1Ch] [ebp-88h]
  int v250; // [esp+1Ch] [ebp-88h]
  int v251; // [esp+1Ch] [ebp-88h]
  int v252; // [esp+1Ch] [ebp-88h]
  int v253; // [esp+1Ch] [ebp-88h]
  int v254; // [esp+1Ch] [ebp-88h]
  int v255; // [esp+1Ch] [ebp-88h]
  int v256; // [esp+1Ch] [ebp-88h]
  int v257; // [esp+1Ch] [ebp-88h]
  int v258; // [esp+1Ch] [ebp-88h]
  int v259; // [esp+1Ch] [ebp-88h]
  int v260; // [esp+1Ch] [ebp-88h]
  int v261; // [esp+1Ch] [ebp-88h]
  int v262; // [esp+1Ch] [ebp-88h]
  int v263; // [esp+1Ch] [ebp-88h]
  int v264; // [esp+1Ch] [ebp-88h]
  int v265; // [esp+1Ch] [ebp-88h]
  int v266; // [esp+1Ch] [ebp-88h]
  int v267; // [esp+1Ch] [ebp-88h]
  int v268; // [esp+1Ch] [ebp-88h]
  int v269; // [esp+1Ch] [ebp-88h]
  int v270; // [esp+1Ch] [ebp-88h]
  int v271; // [esp+1Ch] [ebp-88h]
  int v272; // [esp+1Ch] [ebp-88h]
  int v273; // [esp+1Ch] [ebp-88h]
  int v274; // [esp+1Ch] [ebp-88h]
  int v275; // [esp+1Ch] [ebp-88h]
  int v276; // [esp+1Ch] [ebp-88h]
  int v277; // [esp+1Ch] [ebp-88h]
  int v278; // [esp+1Ch] [ebp-88h]
  int v279; // [esp+1Ch] [ebp-88h]
  int v280; // [esp+1Ch] [ebp-88h]
  int v281; // [esp+1Ch] [ebp-88h]
  int v282; // [esp+1Ch] [ebp-88h]
  int v283; // [esp+1Ch] [ebp-88h]
  int v284; // [esp+1Ch] [ebp-88h]
  int v285; // [esp+1Ch] [ebp-88h]
  int v286; // [esp+1Ch] [ebp-88h]
  int v287; // [esp+1Ch] [ebp-88h]
  int v288; // [esp+1Ch] [ebp-88h]
  int v289; // [esp+1Ch] [ebp-88h]
  int v290; // [esp+20h] [ebp-84h]
  int v291; // [esp+20h] [ebp-84h]
  int v292; // [esp+20h] [ebp-84h]
  int v293; // [esp+20h] [ebp-84h]
  int v294; // [esp+20h] [ebp-84h]
  int v295; // [esp+20h] [ebp-84h]
  int v296; // [esp+20h] [ebp-84h]
  int v297; // [esp+20h] [ebp-84h]
  int v298; // [esp+20h] [ebp-84h]
  int v299; // [esp+20h] [ebp-84h]
  int v300; // [esp+20h] [ebp-84h]
  int v301; // [esp+20h] [ebp-84h]
  int v302; // [esp+20h] [ebp-84h]
  int v303; // [esp+20h] [ebp-84h]
  int v304; // [esp+20h] [ebp-84h]
  int v305; // [esp+20h] [ebp-84h]
  int v306; // [esp+20h] [ebp-84h]
  int v307; // [esp+20h] [ebp-84h]
  int v308; // [esp+20h] [ebp-84h]
  int v309; // [esp+20h] [ebp-84h]
  int v310; // [esp+20h] [ebp-84h]
  int v311; // [esp+20h] [ebp-84h]
  int v312; // [esp+20h] [ebp-84h]
  int v313; // [esp+20h] [ebp-84h]
  int v314; // [esp+20h] [ebp-84h]
  int v315; // [esp+20h] [ebp-84h]
  int v316; // [esp+20h] [ebp-84h]
  int v317; // [esp+20h] [ebp-84h]
  int v318; // [esp+20h] [ebp-84h]
  int v319; // [esp+20h] [ebp-84h]
  int v320; // [esp+20h] [ebp-84h]
  int v321; // [esp+20h] [ebp-84h]
  int v322; // [esp+20h] [ebp-84h]
  int v323; // [esp+20h] [ebp-84h]
  int v324; // [esp+20h] [ebp-84h]
  int v325; // [esp+20h] [ebp-84h]
  int v326; // [esp+20h] [ebp-84h]
  int v327; // [esp+20h] [ebp-84h]
  int v328; // [esp+20h] [ebp-84h]
  int v329; // [esp+20h] [ebp-84h]
  int v330; // [esp+20h] [ebp-84h]
  int v331; // [esp+20h] [ebp-84h]
  int v332; // [esp+24h] [ebp-80h]
  int v333; // [esp+24h] [ebp-80h]
  int v334; // [esp+24h] [ebp-80h]
  int v335; // [esp+24h] [ebp-80h]
  int v336; // [esp+24h] [ebp-80h]
  int v337; // [esp+24h] [ebp-80h]
  int v338; // [esp+24h] [ebp-80h]
  int v339; // [esp+24h] [ebp-80h]
  int v340; // [esp+24h] [ebp-80h]
  int v341; // [esp+24h] [ebp-80h]
  int v342; // [esp+24h] [ebp-80h]
  int v343; // [esp+24h] [ebp-80h]
  int v344; // [esp+24h] [ebp-80h]
  int v345; // [esp+24h] [ebp-80h]
  int v346; // [esp+24h] [ebp-80h]
  int v347; // [esp+24h] [ebp-80h]
  int v348; // [esp+24h] [ebp-80h]
  int v349; // [esp+24h] [ebp-80h]
  int v350; // [esp+24h] [ebp-80h]
  int v351; // [esp+24h] [ebp-80h]
  int v352; // [esp+24h] [ebp-80h]
  int v353; // [esp+24h] [ebp-80h]
  int v354; // [esp+24h] [ebp-80h]
  int v355; // [esp+24h] [ebp-80h]
  int v356; // [esp+24h] [ebp-80h]
  int v357; // [esp+24h] [ebp-80h]
  int v358; // [esp+24h] [ebp-80h]
  int v359; // [esp+24h] [ebp-80h]
  int v360; // [esp+24h] [ebp-80h]
  int v361; // [esp+24h] [ebp-80h]
  int v362; // [esp+24h] [ebp-80h]
  int v363; // [esp+24h] [ebp-80h]
  int v364; // [esp+24h] [ebp-80h]
  int v365; // [esp+24h] [ebp-80h]
  int v366; // [esp+24h] [ebp-80h]
  int v367; // [esp+24h] [ebp-80h]
  int v368; // [esp+24h] [ebp-80h]
  int v369; // [esp+28h] [ebp-7Ch]
  int v370; // [esp+28h] [ebp-7Ch]
  int v371; // [esp+28h] [ebp-7Ch]
  int v372; // [esp+28h] [ebp-7Ch]
  int v373; // [esp+28h] [ebp-7Ch]
  int v374; // [esp+28h] [ebp-7Ch]
  int v375; // [esp+28h] [ebp-7Ch]
  int v376; // [esp+2Ch] [ebp-78h]
  int v377; // [esp+2Ch] [ebp-78h]
  int v378; // [esp+2Ch] [ebp-78h]
  int v379; // [esp+2Ch] [ebp-78h]
  int v380; // [esp+2Ch] [ebp-78h]
  int v381; // [esp+2Ch] [ebp-78h]
  int v382; // [esp+2Ch] [ebp-78h]
  int v383; // [esp+2Ch] [ebp-78h]
  int v384; // [esp+30h] [ebp-74h]
  int v385; // [esp+30h] [ebp-74h]
  int v386; // [esp+30h] [ebp-74h]
  int v387; // [esp+30h] [ebp-74h]
  int v388; // [esp+30h] [ebp-74h]
  int v389; // [esp+30h] [ebp-74h]
  int v390; // [esp+30h] [ebp-74h]
  int v391; // [esp+30h] [ebp-74h]
  int v392; // [esp+34h] [ebp-70h]
  int v393; // [esp+34h] [ebp-70h]
  int v394; // [esp+34h] [ebp-70h]
  int v395; // [esp+34h] [ebp-70h]
  int v396; // [esp+34h] [ebp-70h]
  int v397; // [esp+34h] [ebp-70h]
  int v398; // [esp+34h] [ebp-70h]
  int v399; // [esp+34h] [ebp-70h]
  int v400; // [esp+38h] [ebp-6Ch]
  int v401; // [esp+38h] [ebp-6Ch]
  int v402; // [esp+38h] [ebp-6Ch]
  int v403; // [esp+38h] [ebp-6Ch]
  int v404; // [esp+38h] [ebp-6Ch]
  int v405; // [esp+38h] [ebp-6Ch]
  int v406; // [esp+38h] [ebp-6Ch]
  int v407; // [esp+38h] [ebp-6Ch]
  int v408; // [esp+3Ch] [ebp-68h]
  int v409; // [esp+3Ch] [ebp-68h]
  int v410; // [esp+3Ch] [ebp-68h]
  int v411; // [esp+3Ch] [ebp-68h]
  int v412; // [esp+3Ch] [ebp-68h]
  int v413; // [esp+3Ch] [ebp-68h]
  int v414; // [esp+3Ch] [ebp-68h]
  int v415; // [esp+3Ch] [ebp-68h]
  int v416; // [esp+40h] [ebp-64h]
  int v417; // [esp+40h] [ebp-64h]
  int v418; // [esp+40h] [ebp-64h]
  int v419; // [esp+40h] [ebp-64h]
  int v420; // [esp+40h] [ebp-64h]
  int v421; // [esp+40h] [ebp-64h]
  int v422; // [esp+40h] [ebp-64h]
  int v423; // [esp+40h] [ebp-64h]
  int v424; // [esp+44h] [ebp-60h]
  int v425; // [esp+44h] [ebp-60h]
  int v426; // [esp+44h] [ebp-60h]
  int v427; // [esp+44h] [ebp-60h]
  int v428; // [esp+44h] [ebp-60h]
  int v429; // [esp+44h] [ebp-60h]
  int v430; // [esp+44h] [ebp-60h]
  int v431; // [esp+44h] [ebp-60h]
  int v432; // [esp+48h] [ebp-5Ch]
  int v433; // [esp+48h] [ebp-5Ch]
  int v434; // [esp+48h] [ebp-5Ch]
  int v435; // [esp+48h] [ebp-5Ch]
  int v436; // [esp+48h] [ebp-5Ch]
  int v437; // [esp+48h] [ebp-5Ch]
  int v438; // [esp+48h] [ebp-5Ch]
  int v439; // [esp+48h] [ebp-5Ch]
  int v440; // [esp+4Ch] [ebp-58h]
  int v441; // [esp+4Ch] [ebp-58h]
  int v442; // [esp+4Ch] [ebp-58h]
  int v443; // [esp+4Ch] [ebp-58h]
  int v444; // [esp+4Ch] [ebp-58h]
  int v445; // [esp+4Ch] [ebp-58h]
  int v446; // [esp+4Ch] [ebp-58h]
  int v447; // [esp+4Ch] [ebp-58h]
  int v448; // [esp+50h] [ebp-54h]
  int v449; // [esp+50h] [ebp-54h]
  int v450; // [esp+50h] [ebp-54h]
  int v451; // [esp+50h] [ebp-54h]
  int v452; // [esp+50h] [ebp-54h]
  int v453; // [esp+50h] [ebp-54h]
  int v454; // [esp+50h] [ebp-54h]
  int v455; // [esp+50h] [ebp-54h]
  int v456; // [esp+54h] [ebp-50h]
  int v457; // [esp+54h] [ebp-50h]
  int v458; // [esp+54h] [ebp-50h]
  int v459; // [esp+54h] [ebp-50h]
  int v460; // [esp+54h] [ebp-50h]
  int v461; // [esp+54h] [ebp-50h]
  int v462; // [esp+54h] [ebp-50h]
  int v463; // [esp+54h] [ebp-50h]
  int v464; // [esp+58h] [ebp-4Ch]
  int v465; // [esp+58h] [ebp-4Ch]
  int v466; // [esp+58h] [ebp-4Ch]
  int v467; // [esp+58h] [ebp-4Ch]
  int v468; // [esp+58h] [ebp-4Ch]
  int v469; // [esp+58h] [ebp-4Ch]
  int v470; // [esp+5Ch] [ebp-48h]
  int v471; // [esp+5Ch] [ebp-48h]
  int v472; // [esp+5Ch] [ebp-48h]
  int v473; // [esp+5Ch] [ebp-48h]
  int v474; // [esp+60h] [ebp-44h]
  int v475; // [esp+60h] [ebp-44h]
  int v476; // [esp+60h] [ebp-44h]
  int v477; // [esp+60h] [ebp-44h]
  int v478; // [esp+64h] [ebp-40h]
  int v479; // [esp+64h] [ebp-40h]
  int v480; // [esp+64h] [ebp-40h]
  int v481; // [esp+64h] [ebp-40h]
  int v482; // [esp+64h] [ebp-40h]
  int v483; // [esp+64h] [ebp-40h]
  unsigned int v484; // [esp+68h] [ebp-3Ch]
  int v485; // [esp+6Ch] [ebp-38h]
  int v486; // [esp+6Ch] [ebp-38h]
  int v487; // [esp+70h] [ebp-34h]
  int v488; // [esp+74h] [ebp-30h]
  int v489; // [esp+7Ch] [ebp-28h]
  int v490; // [esp+80h] [ebp-24h]
  int v491; // [esp+84h] [ebp-20h]
  int v492; // [esp+88h] [ebp-1Ch]
  int v493; // [esp+8Ch] [ebp-18h]
  int v494; // [esp+90h] [ebp-14h]
  int v495; // [esp+94h] [ebp-10h]
  int v496; // [esp+98h] [ebp-Ch]
  int v497; // [esp+9Ch] [ebp-8h]
  int v498; // [esp+A0h] [ebp-4h]

  result = a2;
  v4 = a1[2];
  v5 = a1[1];
  v6 = a1[4] + __ROL4__(*a1, 5) + *a2 + (a1[3] ^ v5 & (v4 ^ a1[3])) + 1518500249;
  v247 = __ROL4__(v5, 30);
  v125 = a1[3] + __ROL4__(v6, 5) + a2[1] + (v4 ^ *a1 & (v247 ^ v4)) + 1518500249;
  v7 = __ROL4__(*a1, 30);
  v8 = v4 + __ROL4__(v125, 5) + a2[2] + (v247 ^ v6 & (v7 ^ v247)) + 1518500249;
  v332 = __ROL4__(v6, 30);
  v9 = __ROL4__(v8, 5) + a2[3] + (v7 ^ v125 & (v7 ^ v332)) + v247 + 1518500249;
  v126 = __ROL4__(v125, 30);
  v10 = v7 + __ROL4__(v9, 5) + a2[4] + (v332 ^ v8 & (v126 ^ v332)) + 1518500249;
  v209 = __ROL4__(v8, 30);
  v11 = v332 + __ROL4__(v10, 5) + a2[5] + (v126 ^ v9 & (v209 ^ v126)) + 1518500249;
  v290 = __ROL4__(v9, 30);
  v12 = v126 + __ROL4__(v11, 5) + a2[6] + (v209 ^ v10 & (v290 ^ v209)) + 1518500249;
  v248 = __ROL4__(v10, 30);
  v13 = v209 + __ROL4__(v12, 5) + a2[7] + (v290 ^ v11 & (v248 ^ v290)) + 1518500249;
  v171 = __ROL4__(v11, 30);
  v14 = v290 + __ROL4__(v13, 5) + a2[8] + (v248 ^ v12 & (v171 ^ v248)) + 1518500249;
  v333 = __ROL4__(v12, 30);
  v15 = v248 + __ROL4__(v14, 5) + a2[9] + (v171 ^ v13 & (v171 ^ v333)) + 1518500249;
  v127 = __ROL4__(v13, 30);
  v16 = v171 + __ROL4__(v15, 5) + a2[10] + (v333 ^ v14 & (v127 ^ v333)) + 1518500249;
  v210 = __ROL4__(v14, 30);
  v17 = v333 + __ROL4__(v16, 5) + a2[11] + (v127 ^ v15 & (v210 ^ v127)) + 1518500249;
  v291 = __ROL4__(v15, 30);
  v18 = v127 + __ROL4__(v17, 5) + a2[12] + (v210 ^ v16 & (v291 ^ v210)) + 1518500249;
  v249 = __ROL4__(v16, 30);
  v19 = a2[14];
  v172 = __ROL4__(v17, 30);
  v128 = v210 + __ROL4__(v18, 5) + a2[13] + (v291 ^ v17 & (v249 ^ v291)) + 1518500249;
  v20 = __ROL4__(v128, 5) + v19 + (v249 ^ v18 & (v172 ^ v249));
  v21 = __ROL4__(v18, 30);
  v22 = a2[15];
  v211 = v291 + v20 + 1518500249;
  v292 = __ROL4__(v211, 5) + v22 + (v172 ^ v128 & (v172 ^ v21)) + v249 + 1518500249;
  v129 = __ROL4__(v128, 30);
  v369 = __ROL4__(*a2 ^ a2[2] ^ a2[8] ^ a2[13], 1);
  v250 = v369 + __ROL4__(v292, 5) + v172 + (v21 ^ v211 & (v129 ^ v21)) + 1518500249;
  v212 = __ROL4__(v211, 30);
  v376 = __ROL4__(a2[1] ^ a2[3] ^ a2[9] ^ v19, 1);
  v173 = v376 + __ROL4__(v250, 5) + v21 + (v129 ^ v292 & (v212 ^ v129)) + 1518500249;
  v293 = __ROL4__(v292, 30);
  v384 = __ROL4__(a2[2] ^ a2[4] ^ a2[10] ^ v22, 1);
  v334 = v384 + __ROL4__(v173, 5) + v129 + (v212 ^ v250 & (v293 ^ v212)) + 1518500249;
  v251 = __ROL4__(v250, 30);
  v392 = __ROL4__(v369 ^ a2[3] ^ a2[5] ^ a2[11], 1);
  v23 = v392 + __ROL4__(v334, 5) + v212 + (v293 ^ v173 & (v251 ^ v293)) + 1518500249;
  v174 = __ROL4__(v173, 30);
  v400 = __ROL4__(v376 ^ a2[4] ^ a2[6] ^ a2[12], 1);
  v130 = v23;
  v24 = v400 + __ROL4__(v23, 5) + v293 + (v174 ^ v251 ^ v334) + 1859775393;
  v335 = __ROL4__(v334, 30);
  v408 = __ROL4__(v384 ^ a2[5] ^ a2[7] ^ a2[13], 1);
  v294 = v408 + __ROL4__(v24, 5) + v251 + (v174 ^ v130 ^ v335) + 1859775393;
  v131 = __ROL4__(v130, 30);
  v416 = __ROL4__(v392 ^ a2[6] ^ a2[8] ^ v19, 1);
  v252 = v416 + __ROL4__(v294, 5) + v174 + (v24 ^ v131 ^ v335) + 1859775393;
  v213 = __ROL4__(v24, 30);
  v424 = __ROL4__(v400 ^ a2[7] ^ a2[9] ^ v22, 1);
  v175 = v424 + __ROL4__(v252, 5) + v335 + (v294 ^ v213 ^ v131) + 1859775393;
  v295 = __ROL4__(v294, 30);
  v432 = __ROL4__(v369 ^ v408 ^ a2[8] ^ a2[10], 1);
  v336 = v432 + __ROL4__(v175, 5) + v131 + (v252 ^ v295 ^ v213) + 1859775393;
  v253 = __ROL4__(v252, 30);
  v440 = __ROL4__(v376 ^ v416 ^ a2[9] ^ a2[11], 1);
  v132 = v440 + __ROL4__(v336, 5) + v213 + (v175 ^ v253 ^ v295) + 1859775393;
  v176 = __ROL4__(v175, 30);
  v448 = __ROL4__(v384 ^ v424 ^ a2[10] ^ a2[12], 1);
  v25 = v448 + __ROL4__(v132, 5) + v295 + (v176 ^ v253 ^ v336) + 1859775393;
  v337 = __ROL4__(v336, 30);
  v456 = __ROL4__(v392 ^ v432 ^ a2[11] ^ a2[13], 1);
  v296 = v456 + __ROL4__(v25, 5) + v253 + (v176 ^ v132 ^ v337) + 1859775393;
  v133 = __ROL4__(v132, 30);
  v464 = __ROL4__(v400 ^ v440 ^ a2[12] ^ v19, 1);
  v254 = v464 + __ROL4__(v296, 5) + v176 + (v25 ^ v133 ^ v337) + 1859775393;
  v214 = __ROL4__(v25, 30);
  v470 = __ROL4__(v408 ^ v448 ^ a2[13] ^ v22, 1);
  v26 = v470 + __ROL4__(v254, 5) + v337 + (v296 ^ v214 ^ v133) + 1859775393;
  v297 = __ROL4__(v296, 30);
  v27 = __ROL4__(v369 ^ v416 ^ v456 ^ v19, 1);
  v338 = v27 + __ROL4__(v26, 5) + v133 + (v254 ^ v297 ^ v214) + 1859775393;
  v255 = __ROL4__(v254, 30);
  v478 = __ROL4__(v376 ^ v424 ^ v464 ^ v22, 1);
  v177 = __ROL4__(v26, 30);
  v134 = v478 + __ROL4__(v338, 5) + v214 + (v26 ^ v255 ^ v297) + 1859775393;
  v370 = __ROL4__(v369 ^ v384 ^ v432 ^ v470, 1);
  v215 = v370 + __ROL4__(v134, 5) + v297 + (v177 ^ v255 ^ v338) + 1859775393;
  v339 = __ROL4__(v338, 30);
  v377 = __ROL4__(v376 ^ v392 ^ v440 ^ v27, 1);
  v28 = v377 + __ROL4__(v215, 5) + v255 + (v177 ^ v134 ^ v339) + 1859775393;
  v135 = __ROL4__(v134, 30);
  v385 = __ROL4__(v384 ^ v400 ^ v448 ^ v478, 1);
  v29 = __ROL4__(v28, 5) + v177 + (v215 ^ v135 ^ v339);
  v216 = __ROL4__(v215, 30);
  v256 = v385 + v29 + 1859775393;
  v393 = __ROL4__(v370 ^ v392 ^ v408 ^ v456, 1);
  v298 = __ROL4__(v28, 30);
  v401 = __ROL4__(v377 ^ v400 ^ v416 ^ v464, 1);
  v178 = v393 + __ROL4__(v256, 5) + v339 + (v28 ^ v216 ^ v135) + 1859775393;
  v30 = v401 + __ROL4__(v178, 5) + v135 + (v256 ^ v298 ^ v216) + 1859775393;
  v257 = __ROL4__(v256, 30);
  v409 = __ROL4__(v385 ^ v408 ^ v424 ^ v470, 1);
  v31 = v409 + __ROL4__(v30, 5) + v216 + (v178 ^ v257 ^ v298) + 1859775393;
  v179 = __ROL4__(v178, 30);
  v136 = v31;
  v32 = __ROL4__(v31, 5);
  v417 = __ROL4__(v393 ^ v416 ^ v432 ^ v27, 1);
  v33 = __ROL4__(v30, 30);
  v34 = v417 + v32 + v298 + (v179 ^ v257 ^ v30) + 1859775393;
  v425 = __ROL4__(v401 ^ v424 ^ v440 ^ v478, 1);
  v35 = v425 + __ROL4__(v34, 5) + v257 + (v179 ^ v136 ^ v33) + 1859775393;
  v433 = __ROL4__(v370 ^ v409 ^ v432 ^ v448, 1);
  v137 = __ROL4__(v136, 30);
  v299 = v35;
  v441 = __ROL4__(v377 ^ v417 ^ v440 ^ v456, 1);
  v217 = __ROL4__(v34, 30);
  v258 = __ROL4__(v35, 5) + v433 + v179 + (v34 & v137 | v33 & (v34 | v137)) - 1894007588;
  v36 = __ROL4__(v258, 5) + v441 + v33 + (v299 & v217 | v137 & (v299 | v217)) - 1894007588;
  v449 = __ROL4__(v385 ^ v425 ^ v448 ^ v464, 1);
  v300 = __ROL4__(v299, 30);
  v180 = v36;
  v37 = __ROL4__(v36, 5) + v449 + v137 + (v258 & v300 | v217 & (v258 | v300)) - 1894007588;
  v457 = __ROL4__(v393 ^ v433 ^ v456 ^ v470, 1);
  v259 = __ROL4__(v258, 30);
  v340 = v37;
  v38 = __ROL4__(v37, 5) + v457 + v217 + (v180 & v259 | v300 & (v180 | v259)) - 1894007588;
  v181 = __ROL4__(v180, 30);
  v465 = __ROL4__(v401 ^ v441 ^ v464 ^ v27, 1);
  v39 = __ROL4__(v38, 5) + v465 + v300 + (v181 & v340 | v259 & (v181 | v340)) - 1894007588;
  v471 = __ROL4__(v409 ^ v449 ^ v470 ^ v478, 1);
  v341 = __ROL4__(v340, 30);
  v40 = __ROL4__(v39, 5) + v471 + v259 + (v38 & v341 | v181 & (v38 | v341)) - 1894007588;
  v138 = __ROL4__(v38, 30);
  v474 = __ROL4__(v370 ^ v417 ^ v457 ^ v27, 1);
  v260 = v474 + v181 + (v39 & v138 | v341 & (v39 | v138)) + __ROL4__(v40, 5) - 1894007588;
  v218 = __ROL4__(v39, 30);
  v479 = __ROL4__(v377 ^ v425 ^ v465 ^ v478, 1);
  v301 = __ROL4__(v40, 30);
  v182 = v479 + v341 + (v40 & v218 | v138 & (v40 | v218)) + __ROL4__(v260, 5) - 1894007588;
  v371 = __ROL4__(v370 ^ v385 ^ v433 ^ v471, 1);
  v41 = v371 + v138 + (v260 & v301 | v218 & (v260 | v301)) + __ROL4__(v182, 5) - 1894007588;
  v261 = __ROL4__(v260, 30);
  v378 = __ROL4__(v377 ^ v393 ^ v441 ^ v474, 1);
  v42 = v378 + v218 + (v182 & v261 | v301 & (v182 | v261)) + __ROL4__(v41, 5) - 1894007588;
  v183 = __ROL4__(v182, 30);
  v139 = v42;
  v386 = __ROL4__(v385 ^ v401 ^ v449 ^ v479, 1);
  v43 = __ROL4__(v42, 5) + v386 + v301 + (v183 & v41 | v261 & (v183 | v41)) - 1894007588;
  v44 = __ROL4__(v41, 30);
  v394 = __ROL4__(v371 ^ v393 ^ v409 ^ v457, 1);
  v302 = v394 + v261 + (v139 & v44 | v183 & (v139 | v44)) + __ROL4__(v43, 5) - 1894007588;
  v140 = __ROL4__(v139, 30);
  v402 = __ROL4__(v378 ^ v401 ^ v417 ^ v465, 1);
  v219 = __ROL4__(v43, 30);
  v262 = v402 + v183 + (v43 & v140 | v44 & (v43 | v140)) + __ROL4__(v302, 5) - 1894007588;
  v410 = __ROL4__(v386 ^ v409 ^ v425 ^ v471, 1);
  v45 = v410 + v44 + (v302 & v219 | v140 & (v302 | v219)) + __ROL4__(v262, 5) - 1894007588;
  v303 = __ROL4__(v302, 30);
  v418 = __ROL4__(v394 ^ v417 ^ v433 ^ v474, 1);
  v46 = __ROL4__(v45, 5) + v418 + v140 + (v262 & v303 | v219 & (v262 | v303)) - 1894007588;
  v263 = __ROL4__(v262, 30);
  v426 = __ROL4__(v402 ^ v425 ^ v441 ^ v479, 1);
  v184 = __ROL4__(v45, 30);
  v141 = v426 + v219 + (v45 & v263 | v303 & (v45 | v263)) + __ROL4__(v46, 5) - 1894007588;
  v434 = __ROL4__(v371 ^ v410 ^ v433 ^ v449, 1);
  v220 = __ROL4__(v141, 5) + v434 + v303 + (v184 & v46 | v263 & (v184 | v46)) - 1894007588;
  v342 = __ROL4__(v46, 30);
  v442 = __ROL4__(v378 ^ v418 ^ v441 ^ v457, 1);
  v304 = v442 + v263 + (v141 & v342 | v184 & (v141 | v342)) + __ROL4__(v220, 5) - 1894007588;
  v142 = __ROL4__(v141, 30);
  v450 = __ROL4__(v386 ^ v426 ^ v449 ^ v465, 1);
  v47 = v450 + v184 + (v220 & v142 | v342 & (v220 | v142)) + __ROL4__(v304, 5) - 1894007588;
  v221 = __ROL4__(v220, 30);
  v458 = __ROL4__(v394 ^ v434 ^ v457 ^ v471, 1);
  v48 = __ROL4__(v304, 30);
  v49 = v48 ^ v221;
  v185 = v458 + v342 + (v304 & v221 | v142 & (v304 | v221)) + __ROL4__(v47, 5) - 1894007588;
  v305 = v48;
  v50 = __ROL4__(v402 ^ v442 ^ v465 ^ v474, 1);
  v264 = __ROL4__(v47, 30);
  v343 = v50 + (v47 ^ v49) + v142 + __ROL4__(v185, 5) - 899497514;
  v51 = __ROL4__(v410 ^ v450 ^ v471 ^ v479, 1);
  v52 = v51 + (v185 ^ v264 ^ v305) + v221 + __ROL4__(v343, 5) - 899497514;
  v186 = __ROL4__(v185, 30);
  v475 = __ROL4__(v371 ^ v418 ^ v458 ^ v474, 1);
  v143 = v52;
  v53 = v475 + (v186 ^ v264 ^ v343) + v305 + __ROL4__(v52, 5) - 899497514;
  v344 = __ROL4__(v343, 30);
  v480 = __ROL4__(v378 ^ v426 ^ v50 ^ v479, 1);
  v54 = v480 + (v186 ^ v143 ^ v344);
  v144 = __ROL4__(v143, 30);
  v306 = v264 + __ROL4__(v53, 5) + v54 - 899497514;
  v372 = __ROL4__(v371 ^ v386 ^ v434 ^ v51, 1);
  v222 = __ROL4__(v53, 30);
  v265 = v372 + (v53 ^ v144 ^ v344) + v186 + __ROL4__(v306, 5) - 899497514;
  v379 = __ROL4__(v378 ^ v394 ^ v442 ^ v475, 1);
  v187 = v379 + (v306 ^ v222 ^ v144) + v344 + __ROL4__(v265, 5) - 899497514;
  v307 = __ROL4__(v306, 30);
  v387 = __ROL4__(v386 ^ v402 ^ v450 ^ v480, 1);
  v55 = v387 + (v265 ^ v307 ^ v222) + v144 + __ROL4__(v187, 5) - 899497514;
  v266 = __ROL4__(v265, 30);
  v345 = v55;
  v395 = __ROL4__(v372 ^ v394 ^ v410 ^ v458, 1);
  v56 = v395 + (v187 ^ v266 ^ v307) + v222 + __ROL4__(v55, 5) - 899497514;
  v188 = __ROL4__(v187, 30);
  v403 = __ROL4__(v379 ^ v402 ^ v418 ^ v50, 1);
  v145 = v56;
  v57 = v403 + (v188 ^ v266 ^ v345) + v307 + __ROL4__(v56, 5) - 899497514;
  v346 = __ROL4__(v345, 30);
  v411 = __ROL4__(v387 ^ v410 ^ v426 ^ v51, 1);
  v308 = v266 + __ROL4__(v57, 5) + v411 + (v188 ^ v145 ^ v346) - 899497514;
  v146 = __ROL4__(v145, 30);
  v419 = __ROL4__(v395 ^ v418 ^ v434 ^ v475, 1);
  v223 = __ROL4__(v57, 30);
  v267 = v419 + (v57 ^ v146 ^ v346) + v188 + __ROL4__(v308, 5) - 899497514;
  v427 = __ROL4__(v403 ^ v426 ^ v442 ^ v480, 1);
  v58 = v427 + (v308 ^ v223 ^ v146) + v346 + __ROL4__(v267, 5) - 899497514;
  v309 = __ROL4__(v308, 30);
  v189 = v58;
  v435 = __ROL4__(v372 ^ v411 ^ v434 ^ v450, 1);
  v59 = v435 + (v267 ^ v309 ^ v223) + v146 + __ROL4__(v58, 5) - 899497514;
  v268 = __ROL4__(v267, 30);
  v443 = __ROL4__(v379 ^ v419 ^ v442 ^ v458, 1);
  v147 = v443 + (v189 ^ v268 ^ v309) + v223 + __ROL4__(v59, 5) - 899497514;
  v190 = __ROL4__(v189, 30);
  v451 = __ROL4__(v387 ^ v427 ^ v450 ^ v50, 1);
  v347 = __ROL4__(v59, 30);
  v224 = v451 + (v190 ^ v268 ^ v59) + v309 + __ROL4__(v147, 5) - 899497514;
  v459 = __ROL4__(v395 ^ v435 ^ v458 ^ v51, 1);
  v60 = v459 + (v190 ^ v147 ^ v347);
  v148 = __ROL4__(v147, 30);
  v466 = __ROL4__(v403 ^ v443 ^ v50 ^ v475, 1);
  v310 = v268 + __ROL4__(v224, 5) + v60 - 899497514;
  v61 = v466 + (v224 ^ v148 ^ v347) + v190 + __ROL4__(v310, 5) - 899497514;
  v225 = __ROL4__(v224, 30);
  v62 = __ROL4__(v411 ^ v451 ^ v51 ^ v480, 1) + (v310 ^ v225 ^ v148) + v347 + __ROL4__(v61, 5) - 899497514;
  v311 = __ROL4__(v310, 30);
  v63 = v148 + __ROL4__(v62, 5) + __ROL4__(v372 ^ v419 ^ v459 ^ v475, 1) + (v61 ^ v311 ^ v225) - 899497514;
  v269 = __ROL4__(v61, 30);
  v64 = v63 + a1[1];
  *a1 = v225 + __ROL4__(v63, 5) + __ROL4__(v379 ^ v427 ^ v466 ^ v480, 1) + *a1 + (v62 ^ v269 ^ v311) - 899497514;
  a1[1] = v64;
  v65 = v64;
  a1[2] += __ROL4__(v62, 30);
  a1[3] += v269;
  a1[4] += v311;
  if ( a3 - 64 > 0 )
  {
    v484 = (unsigned int)(a3 - 64 + 63) >> 6;
    do
    {
      v66 = a1[2];
      v67 = result[16];
      result += 16;
      v485 = result[1];
      v68 = __ROL4__(*a1, 5) + v67 + (a1[3] ^ v65 & (v66 ^ a1[3])) + a1[4] + 1518500249;
      v69 = __ROL4__(a1[1], 30);
      v498 = result[2];
      v70 = __ROL4__(*a1, 30);
      v149 = v485 + __ROL4__(v68, 5) + a1[3] + (v66 ^ *a1 & (v69 ^ v66)) + 1518500249;
      v348 = __ROL4__(v68, 30);
      v497 = result[3];
      v226 = __ROL4__(v149, 5) + v498 + (v69 ^ v68 & (v70 ^ v69)) + v66 + 1518500249;
      v494 = result[4];
      v71 = __ROL4__(v226, 5) + v497 + (v70 ^ v149 & (v70 ^ v348)) + v69 + 1518500249;
      v150 = __ROL4__(v149, 30);
      v72 = v70 + __ROL4__(v71, 5) + v494 + (v348 ^ v226 & (v150 ^ v348)) + 1518500249;
      v227 = __ROL4__(v226, 30);
      v496 = result[5];
      v73 = v348 + __ROL4__(v72, 5) + v496 + (v150 ^ v71 & (v227 ^ v150)) + 1518500249;
      v312 = __ROL4__(v71, 30);
      v493 = result[6];
      v74 = v150 + __ROL4__(v73, 5) + v493 + (v227 ^ v72 & (v312 ^ v227)) + 1518500249;
      v270 = __ROL4__(v72, 30);
      v495 = result[7];
      v75 = v227 + __ROL4__(v74, 5) + v495 + (v312 ^ v73 & (v270 ^ v312)) + 1518500249;
      v191 = __ROL4__(v73, 30);
      v489 = result[8];
      v76 = v312 + __ROL4__(v75, 5) + v489 + (v270 ^ v74 & (v191 ^ v270)) + 1518500249;
      v349 = __ROL4__(v74, 30);
      v490 = result[9];
      v77 = v270 + __ROL4__(v76, 5) + v490 + (v191 ^ v75 & (v191 ^ v349)) + 1518500249;
      v151 = __ROL4__(v75, 30);
      v492 = result[10];
      v78 = v191 + __ROL4__(v77, 5) + v492 + (v349 ^ v76 & (v151 ^ v349)) + 1518500249;
      v228 = __ROL4__(v76, 30);
      v488 = result[11];
      v79 = v349 + __ROL4__(v78, 5) + v488 + (v151 ^ v77 & (v228 ^ v151)) + 1518500249;
      v313 = __ROL4__(v77, 30);
      v491 = result[12];
      v80 = v151 + __ROL4__(v79, 5) + v491 + (v228 ^ v78 & (v313 ^ v228)) + 1518500249;
      v271 = __ROL4__(v78, 30);
      v487 = result[13];
      v81 = result[14];
      v192 = __ROL4__(v79, 30);
      v152 = v228 + __ROL4__(v80, 5) + v487 + (v313 ^ v79 & (v271 ^ v313)) + 1518500249;
      v82 = result[15];
      v229 = v313 + __ROL4__(v152, 5) + v81 + (v271 ^ v80 & (v192 ^ v271)) + 1518500249;
      v350 = __ROL4__(v80, 30);
      v314 = __ROL4__(v229, 5) + v82 + (v192 ^ v152 & (v192 ^ v350)) + v271 + 1518500249;
      v153 = __ROL4__(v152, 30);
      v83 = __ROL4__(v489 ^ v487 ^ v67 ^ v498, 1);
      v84 = v83 + __ROL4__(v314, 5) + v192 + (v350 ^ v229 & (v153 ^ v350)) + 1518500249;
      v230 = __ROL4__(v229, 30);
      v380 = __ROL4__(v485 ^ v497 ^ v490 ^ v81, 1);
      v193 = v380 + __ROL4__(v84, 5) + v350 + (v153 ^ v314 & (v230 ^ v153)) + 1518500249;
      v315 = __ROL4__(v314, 30);
      v388 = __ROL4__(v494 ^ v492 ^ v82 ^ v498, 1);
      v351 = v388 + __ROL4__(v193, 5) + v153 + (v230 ^ v84 & (v315 ^ v230)) + 1518500249;
      v272 = __ROL4__(v84, 30);
      v396 = __ROL4__(v497 ^ v83 ^ v496 ^ v488, 1);
      v85 = v396 + __ROL4__(v351, 5) + v230 + (v315 ^ v193 & (v272 ^ v315)) + 1518500249;
      v194 = __ROL4__(v193, 30);
      v404 = __ROL4__(v380 ^ v494 ^ v493 ^ v491, 1);
      v154 = v85;
      v86 = v404 + __ROL4__(v85, 5) + v315 + (v194 ^ v272 ^ v351) + 1859775393;
      v352 = __ROL4__(v351, 30);
      v412 = __ROL4__(v388 ^ v496 ^ v495 ^ v487, 1);
      v316 = v412 + __ROL4__(v86, 5) + v272 + (v194 ^ v154 ^ v352) + 1859775393;
      v155 = __ROL4__(v154, 30);
      v420 = __ROL4__(v396 ^ v493 ^ v489 ^ v81, 1);
      v273 = v420 + __ROL4__(v316, 5) + v194 + (v86 ^ v155 ^ v352) + 1859775393;
      v231 = __ROL4__(v86, 30);
      v428 = __ROL4__(v404 ^ v495 ^ v490 ^ v82, 1);
      v195 = v428 + __ROL4__(v273, 5) + v352 + (v316 ^ v231 ^ v155) + 1859775393;
      v317 = __ROL4__(v316, 30);
      v436 = __ROL4__(v83 ^ v412 ^ v489 ^ v492, 1);
      v353 = v436 + __ROL4__(v195, 5) + v155 + (v273 ^ v317 ^ v231) + 1859775393;
      v274 = __ROL4__(v273, 30);
      v444 = __ROL4__(v380 ^ v420 ^ v490 ^ v488, 1);
      v87 = v444 + __ROL4__(v353, 5) + v231 + (v195 ^ v274 ^ v317) + 1859775393;
      v196 = __ROL4__(v195, 30);
      v452 = __ROL4__(v388 ^ v428 ^ v492 ^ v491, 1);
      v156 = v87;
      v88 = v452 + __ROL4__(v87, 5) + v317 + (v196 ^ v274 ^ v353) + 1859775393;
      v354 = __ROL4__(v353, 30);
      v460 = __ROL4__(v396 ^ v436 ^ v488 ^ v487, 1);
      v318 = v460 + __ROL4__(v88, 5) + v274 + (v196 ^ v156 ^ v354) + 1859775393;
      v157 = __ROL4__(v156, 30);
      v467 = __ROL4__(v404 ^ v444 ^ v491 ^ v81, 1);
      v275 = v467 + __ROL4__(v318, 5) + v196 + (v88 ^ v157 ^ v354) + 1859775393;
      v232 = __ROL4__(v88, 30);
      v472 = __ROL4__(v412 ^ v452 ^ v487 ^ v82, 1);
      v89 = v472 + __ROL4__(v275, 5) + v354 + (v318 ^ v232 ^ v157) + 1859775393;
      v319 = __ROL4__(v318, 30);
      v90 = __ROL4__(v83 ^ v420 ^ v460 ^ v81, 1);
      v355 = v90 + __ROL4__(v89, 5) + v157 + (v275 ^ v319 ^ v232) + 1859775393;
      v276 = __ROL4__(v275, 30);
      v481 = __ROL4__(v380 ^ v428 ^ v467 ^ v82, 1);
      v158 = v481 + __ROL4__(v355, 5) + v232 + (v89 ^ v276 ^ v319) + 1859775393;
      v197 = __ROL4__(v89, 30);
      v373 = __ROL4__(v83 ^ v388 ^ v436 ^ v472, 1);
      v233 = v373 + __ROL4__(v158, 5) + v319 + (v197 ^ v276 ^ v355) + 1859775393;
      v356 = __ROL4__(v355, 30);
      v381 = __ROL4__(v380 ^ v396 ^ v444 ^ v90, 1);
      v91 = v381 + __ROL4__(v233, 5) + v276 + (v197 ^ v158 ^ v356) + 1859775393;
      v159 = __ROL4__(v158, 30);
      v389 = __ROL4__(v388 ^ v404 ^ v452 ^ v481, 1);
      v92 = __ROL4__(v91, 5) + v197 + (v233 ^ v159 ^ v356);
      v234 = __ROL4__(v233, 30);
      v277 = v389 + v92 + 1859775393;
      v397 = __ROL4__(v373 ^ v396 ^ v412 ^ v460, 1);
      v93 = v397 + __ROL4__(v277, 5) + v356 + (v91 ^ v234 ^ v159) + 1859775393;
      v94 = __ROL4__(v91, 30);
      v405 = __ROL4__(v381 ^ v404 ^ v420 ^ v467, 1);
      v95 = v405 + __ROL4__(v93, 5) + v159 + (v277 ^ v94 ^ v234) + 1859775393;
      v486 = __ROL4__(v95, 5);
      v357 = v95;
      v278 = __ROL4__(v277, 30);
      v413 = __ROL4__(v389 ^ v412 ^ v428 ^ v472, 1);
      v96 = __ROL4__(v93, 30);
      v160 = v413 + v486 + v234 + (v93 ^ v278 ^ v94) + 1859775393;
      v421 = __ROL4__(v397 ^ v420 ^ v436 ^ v90, 1);
      v235 = v421 + __ROL4__(v160, 5) + v94 + (v96 ^ v278 ^ v357) + 1859775393;
      v358 = __ROL4__(v357, 30);
      v429 = __ROL4__(v405 ^ v428 ^ v444 ^ v481, 1);
      v320 = v429 + __ROL4__(v235, 5) + v278 + (v96 ^ v160 ^ v358) + 1859775393;
      v437 = __ROL4__(v373 ^ v413 ^ v436 ^ v452, 1);
      v161 = __ROL4__(v160, 30);
      v97 = __ROL4__(v320, 5) + v437 + v96 + (v235 & v161 | v358 & (v235 | v161)) - 1894007588;
      v445 = __ROL4__(v381 ^ v421 ^ v444 ^ v460, 1);
      v236 = __ROL4__(v235, 30);
      v198 = __ROL4__(v97, 5) + v445 + v358 + (v320 & v236 | v161 & (v320 | v236)) - 1894007588;
      v321 = __ROL4__(v320, 30);
      v453 = __ROL4__(v389 ^ v429 ^ v452 ^ v467, 1);
      v98 = __ROL4__(v97, 30);
      v461 = __ROL4__(v397 ^ v437 ^ v460 ^ v472, 1);
      v359 = __ROL4__(v198, 5) + v453 + v161 + (v97 & v321 | v236 & (v97 | v321)) - 1894007588;
      v99 = __ROL4__(v359, 5) + v461 + v236 + (v198 & v98 | v321 & (v198 | v98)) - 1894007588;
      v199 = __ROL4__(v198, 30);
      v468 = __ROL4__(v405 ^ v445 ^ v467 ^ v90, 1);
      v237 = __ROL4__(v99, 5) + v468 + v321 + (v199 & v359 | v98 & (v199 | v359)) - 1894007588;
      v360 = __ROL4__(v359, 30);
      v473 = __ROL4__(v413 ^ v453 ^ v472 ^ v481, 1);
      v100 = __ROL4__(v237, 5) + v473 + v98 + (v99 & v360 | v199 & (v99 | v360)) - 1894007588;
      v162 = __ROL4__(v99, 30);
      v476 = __ROL4__(v373 ^ v421 ^ v461 ^ v90, 1);
      v279 = v476 + v199 + (v237 & v162 | v360 & (v237 | v162)) + __ROL4__(v100, 5) - 1894007588;
      v238 = __ROL4__(v237, 30);
      v482 = __ROL4__(v381 ^ v429 ^ v468 ^ v481, 1);
      v200 = v482 + v360 + (v100 & v238 | v162 & (v100 | v238)) + __ROL4__(v279, 5) - 1894007588;
      v322 = __ROL4__(v100, 30);
      v374 = __ROL4__(v373 ^ v389 ^ v437 ^ v473, 1);
      v101 = v374 + v162 + (v279 & v322 | v238 & (v279 | v322)) + __ROL4__(v200, 5) - 1894007588;
      v280 = __ROL4__(v279, 30);
      v382 = __ROL4__(v381 ^ v397 ^ v445 ^ v476, 1);
      v102 = v382 + v238 + (v200 & v280 | v322 & (v200 | v280)) + __ROL4__(v101, 5) - 1894007588;
      v201 = __ROL4__(v200, 30);
      v390 = __ROL4__(v389 ^ v405 ^ v453 ^ v482, 1);
      v239 = __ROL4__(v102, 5) + v390 + v322 + (v201 & v101 | v280 & (v201 | v101)) - 1894007588;
      v361 = __ROL4__(v101, 30);
      v398 = __ROL4__(v374 ^ v397 ^ v413 ^ v461, 1);
      v163 = __ROL4__(v102, 30);
      v323 = v398 + v280 + (v102 & v361 | v201 & (v102 | v361)) + __ROL4__(v239, 5) - 1894007588;
      v406 = __ROL4__(v382 ^ v405 ^ v421 ^ v468, 1);
      v281 = v406 + v201 + (v239 & v163 | v361 & (v239 | v163)) + __ROL4__(v323, 5) - 1894007588;
      v240 = __ROL4__(v239, 30);
      v414 = __ROL4__(v390 ^ v413 ^ v429 ^ v473, 1);
      v103 = v414 + v361 + (v323 & v240 | v163 & (v323 | v240));
      v324 = __ROL4__(v323, 30);
      v202 = v103 + __ROL4__(v281, 5) - 1894007588;
      v422 = __ROL4__(v398 ^ v421 ^ v437 ^ v476, 1);
      v104 = v422 + v163 + (v281 & v324 | v240 & (v281 | v324)) + __ROL4__(v202, 5) - 1894007588;
      v282 = __ROL4__(v281, 30);
      v430 = __ROL4__(v406 ^ v429 ^ v445 ^ v482, 1);
      v105 = v430 + v240 + (v202 & v282 | v324 & (v202 | v282));
      v203 = __ROL4__(v202, 30);
      v164 = v105 + __ROL4__(v104, 5) - 1894007588;
      v438 = __ROL4__(v374 ^ v414 ^ v437 ^ v453, 1);
      v241 = __ROL4__(v164, 5) + v438 + v324 + (v203 & v104 | v282 & (v203 | v104)) - 1894007588;
      v362 = __ROL4__(v104, 30);
      v446 = __ROL4__(v382 ^ v422 ^ v445 ^ v461, 1);
      v325 = v446 + v282 + (v164 & v362 | v203 & (v164 | v362)) + __ROL4__(v241, 5) - 1894007588;
      v165 = __ROL4__(v164, 30);
      v454 = __ROL4__(v390 ^ v430 ^ v453 ^ v468, 1);
      v106 = v454 + v203 + (v241 & v165 | v362 & (v241 | v165)) + __ROL4__(v325, 5) - 1894007588;
      v242 = __ROL4__(v241, 30);
      v462 = __ROL4__(v398 ^ v438 ^ v461 ^ v473, 1);
      v107 = __ROL4__(v325, 30);
      v108 = v107 ^ v242;
      v204 = v462 + v362 + (v325 & v242 | v165 & (v325 | v242)) + __ROL4__(v106, 5) - 1894007588;
      v326 = v107;
      v109 = __ROL4__(v406 ^ v446 ^ v468 ^ v476, 1);
      v363 = v109 + (v106 ^ v108) + v165 + __ROL4__(v204, 5) - 899497514;
      v283 = __ROL4__(v106, 30);
      v110 = __ROL4__(v414 ^ v454 ^ v473 ^ v482, 1);
      v111 = v110 + (v204 ^ v283 ^ v326) + v242 + __ROL4__(v363, 5) - 899497514;
      v205 = __ROL4__(v204, 30);
      v477 = __ROL4__(v374 ^ v422 ^ v462 ^ v476, 1);
      v166 = v111;
      v112 = v477 + (v205 ^ v283 ^ v363) + v326 + __ROL4__(v111, 5) - 899497514;
      v364 = __ROL4__(v363, 30);
      v483 = __ROL4__(v382 ^ v430 ^ v109 ^ v482, 1);
      v113 = v483 + (v205 ^ v166 ^ v364);
      v167 = __ROL4__(v166, 30);
      v327 = v283 + __ROL4__(v112, 5) + v113 - 899497514;
      v375 = __ROL4__(v374 ^ v390 ^ v438 ^ v110, 1);
      v284 = v375 + (v112 ^ v167 ^ v364) + v205 + __ROL4__(v327, 5) - 899497514;
      v243 = __ROL4__(v112, 30);
      v383 = __ROL4__(v382 ^ v398 ^ v446 ^ v477, 1);
      v114 = v383 + (v327 ^ v243 ^ v167) + v364 + __ROL4__(v284, 5) - 899497514;
      v328 = __ROL4__(v327, 30);
      v206 = v114;
      v391 = __ROL4__(v390 ^ v406 ^ v454 ^ v483, 1);
      v115 = v391 + (v284 ^ v328 ^ v243) + v167 + __ROL4__(v114, 5) - 899497514;
      v285 = __ROL4__(v284, 30);
      v365 = v115;
      v399 = __ROL4__(v375 ^ v398 ^ v414 ^ v462, 1);
      v116 = v399 + (v206 ^ v285 ^ v328) + v243 + __ROL4__(v115, 5) - 899497514;
      v207 = __ROL4__(v206, 30);
      v407 = __ROL4__(v383 ^ v406 ^ v422 ^ v109, 1);
      v244 = v407 + (v207 ^ v285 ^ v365) + v328 + __ROL4__(v116, 5) - 899497514;
      v366 = __ROL4__(v365, 30);
      v415 = __ROL4__(v391 ^ v414 ^ v430 ^ v110, 1);
      v168 = __ROL4__(v116, 30);
      v329 = v285 + __ROL4__(v244, 5) + v415 + (v207 ^ v116 ^ v366) - 899497514;
      v423 = __ROL4__(v399 ^ v422 ^ v438 ^ v477, 1);
      v117 = v423 + (v244 ^ v168 ^ v366) + v207 + __ROL4__(v329, 5) - 899497514;
      v245 = __ROL4__(v244, 30);
      v286 = v117;
      v431 = __ROL4__(v407 ^ v430 ^ v446 ^ v483, 1);
      v118 = v431 + (v329 ^ v245 ^ v168) + v366 + __ROL4__(v117, 5) - 899497514;
      v330 = __ROL4__(v329, 30);
      v439 = __ROL4__(v375 ^ v415 ^ v438 ^ v454, 1);
      v367 = v439 + (v286 ^ v330 ^ v245) + v168 + __ROL4__(v118, 5) - 899497514;
      v287 = __ROL4__(v286, 30);
      v447 = __ROL4__(v383 ^ v423 ^ v446 ^ v462, 1);
      v208 = __ROL4__(v118, 30);
      v455 = __ROL4__(v391 ^ v431 ^ v454 ^ v109, 1);
      v169 = v447 + (v118 ^ v287 ^ v330) + v245 + __ROL4__(v367, 5) - 899497514;
      v119 = v455 + (v208 ^ v287 ^ v367) + v330 + __ROL4__(v169, 5) - 899497514;
      v368 = __ROL4__(v367, 30);
      v463 = __ROL4__(v399 ^ v439 ^ v462 ^ v110, 1);
      v120 = v463 + (v208 ^ v169 ^ v368);
      v170 = __ROL4__(v169, 30);
      v121 = v287 + __ROL4__(v119, 5) + v120 - 899497514;
      v469 = __ROL4__(v407 ^ v447 ^ v109 ^ v477, 1);
      v246 = __ROL4__(v119, 30);
      v288 = v469 + (v119 ^ v170 ^ v368) + v208 + __ROL4__(v121, 5) - 899497514;
      v122 = __ROL4__(v415 ^ v455 ^ v110 ^ v483, 1) + (v121 ^ v246 ^ v170) + v368 + __ROL4__(v288, 5) - 899497514;
      v331 = __ROL4__(v121, 30);
      v123 = v170 + __ROL4__(v122, 5) + __ROL4__(v375 ^ v423 ^ v463 ^ v477, 1) + (v288 ^ v331 ^ v246) - 899497514;
      v289 = __ROL4__(v288, 30);
      v124 = a1[2];
      *a1 = *a1 + (v122 ^ v289 ^ v331) + __ROL4__(v383 ^ v431 ^ v469 ^ v483, 1) + v246 + __ROL4__(v123, 5) - 899497514;
      v65 = v123 + a1[1];
      a1[1] = v65;
      a1[2] = v124 + __ROL4__(v122, 30);
      a1[3] += v289;
      a1[4] += v331;
      --v484;
    }
    while ( v484 );
  }
  return result;
}

//----- (000033C0) --------------------------------------------------------
_BYTE *__cdecl SHA1_Final(_BYTE *a1, int *a2)
{
  int *v2; // ebp
  _DWORD *v3; // ebx
  int v4; // eax
  int v5; // edi
  unsigned __int16 v6; // dx
  int v7; // eax
  int v8; // ecx
  int v9; // ecx
  int v10; // ecx
  int v11; // ecx
  int v12; // ecx
  _BYTE *result; // eax

  v2 = &_end__1__SHA1_Final__9_9;
  v3 = a2 + 7;
  v4 = a2[23] >> 2;
  v5 = a2[v4 + 7];
  switch ( a2[23] & 3 )
  {
    case 0:
      v2 = (int *)((char *)&_end__1__SHA1_Final__9_9 + 1);
      v5 = (unsigned __int8)_end__1__SHA1_Final__9_9 << 24;
      goto $L1654;
    case 1:
$L1654:
      v5 |= *(unsigned __int8 *)v2 << 16;
      v2 = (int *)((char *)v2 + 1);
      goto $L1656;
    case 2:
$L1656:
      LOBYTE(v6) = 0;
      HIBYTE(v6) = *(_BYTE *)v2;
      v5 |= v6;
      v2 = (int *)((char *)v2 + 1);
      goto $L1658;
    case 3:
$L1658:
      v5 |= *(unsigned __int8 *)v2;
      break;
    default:
      break;
  }
  v3[v4] = v5;
  v7 = v4 + 1;
  if ( a2[23] >= 56 )
  {
    if ( v7 < 16 )
      memset(&v3[v7], 0, 4 * (16 - v7));
    sha1_block(a2, v3, 64);
    v7 = 0;
    goto LABEL_11;
  }
  if ( v7 < 14 )
LABEL_11:
    memset(&v3[v7], 0, 4 * (14 - v7));
  a2[21] = a2[6];
  a2[22] = a2[5];
  sha1_block(a2, v3, 64);
  v8 = *a2;
  *a1 = HIBYTE(*a2);
  a1[1] = BYTE2(v8);
  a1[2] = BYTE1(v8);
  a1[3] = v8;
  v9 = a2[1];
  a1[4] = HIBYTE(v9);
  a1[5] = BYTE2(v9);
  a1[6] = BYTE1(v9);
  a1[7] = v9;
  v10 = a2[2];
  a1[8] = HIBYTE(v10);
  a1[9] = BYTE2(v10);
  a1[10] = BYTE1(v10);
  a1[11] = v10;
  v11 = a2[3];
  a1[12] = HIBYTE(v11);
  a1[13] = BYTE2(v11);
  a1[14] = BYTE1(v11);
  a1[15] = v11;
  v12 = a2[4];
  a1[16] = HIBYTE(v12);
  a1[17] = BYTE2(v12);
  result = a1 + 18;
  a1[18] = BYTE1(v12);
  a1[19] = v12;
  a2[23] = 0;
  return result;
}
// 4: using guessed type int _end__1__SHA1_Final__9_9;

// nfuncs=5 queued=5 decompiled=5 lumina nreq=0 worse=0 better=0
// ALL OK, 5 function(s) have been successfully decompiled
