/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void __cdecl SetXTrapStartInfo(char *, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int); // idb
void __cdecl XTrapStart(); // idb
void __cdecl XTrapKeepAlive(); // idb
void __cdecl SetXTrapPatchHttpUrl(char *); // idb
void __cdecl SetOptGameInfo(char *, char *, char *, char *, int); // idb
void __cdecl SetXTrapMgrInfo(char *); // idb
// int _sprintf(char *const Buffer, const char *const Format, ...);
// void __cdecl StartXTrapApi(char *, struct _MDL_START_INFO *, struct _MDL_MSG_INFO *); idb
// int __cdecl ExecuteSynchCmdLine(char *, unsigned int, unsigned int, char *, char *); idb
// void __cdecl GetPathName(char *, char *); idb
// void __cdecl TerminateXTrapIC(); idb
// void __cdecl SendMsgToMgrEx(char *, unsigned int, unsigned int, unsigned int); idb
// DWORD __stdcall GetLastError();
// DWORD __stdcall GetModuleFileNameA(HMODULE hModule, LPSTR lpFilename, DWORD nSize);
// void __cdecl StartXTrapKeepAlive(struct _MDL_MSG_INFO *); idb
// int __cdecl SetGameInfo(struct _GAME_INFO *); idb

//-------------------------------------------------------------------------
// Data declarations

char g_sPatchHttp[264]; // idb
_UNKNOWN g_GameInfo; // weak
char Buffer[64]; // idb
char byte_168[64]; // idb
int dword_1A8; // weak
char byte_1AC[64]; // idb
char byte_1EC[64]; // idb
char byte_22C[68]; // idb
_UNKNOWN g_MdlStartInfo; // weak
int dword_290; // weak
unsigned int dword_294; // idb
int dword_29C; // weak
char byte_2A0[260]; // idb
char byte_3A4[1036]; // idb
char byte_7B0[260]; // idb
__int16 word_8B4; // weak
int dword_8B8; // weak
int dword_8FC; // weak
int dword_900; // weak
int dword_904; // weak
_UNKNOWN g_ApiVerifyData; // weak
int g_bStartXTrap; // weak
char `string'; // idb
// extern unsigned int g_XTrapStatusFlag; weak
// extern unsigned int g_XTrapErrorFlag; idb
// extern unsigned int g_XTrapErrorCode; idb


//----- (00000AAC) --------------------------------------------------------
void __cdecl SetXTrapStartInfo(char *a1, unsigned int a2, unsigned int a3, unsigned int a4, unsigned int a5, unsigned int a6)
{
  void (*v6)(char *const, const char *const, ...); // esi

  v6 = (void (*)(char *const, const char *const, ...))_sprintf;
  _sprintf(Buffer, "%s", a1);
  dword_290 = a2;
  dword_294 = a3;
  dword_8FC = a4;
  dword_900 = a5;
  dword_904 = a6;
  dword_29C = -721420281;
  dword_8B8 = -452984832;
  v6(byte_3A4, "%s", g_sPatchHttp);
  v6(byte_7B0, "%s", "211.115.86.66");
  word_8B4 = 2424;
}
// 290: using guessed type int dword_290;
// 29C: using guessed type int dword_29C;
// 8B4: using guessed type __int16 word_8B4;
// 8B8: using guessed type int dword_8B8;
// 8FC: using guessed type int dword_8FC;
// 900: using guessed type int dword_900;
// 904: using guessed type int dword_904;

//----- (00000B50) --------------------------------------------------------
void __cdecl XTrapStart()
{
  unsigned int v0; // eax
  void (*v1)(char *const, const char *const, ...); // esi
  char v2; // [esp+Ch] [ebp-62Ch] BYREF
  char v3[296]; // [esp+Dh] [ebp-62Bh] BYREF
  __int16 v4; // [esp+135h] [ebp-503h]
  char v5; // [esp+137h] [ebp-501h]
  char Buffer; // [esp+138h] [ebp-500h] BYREF
  char v7[256]; // [esp+139h] [ebp-4FFh] BYREF
  __int16 v8; // [esp+239h] [ebp-3FFh]
  char v9; // [esp+23Bh] [ebp-3FDh]
  char v10; // [esp+23Ch] [ebp-3FCh] BYREF
  char v11[256]; // [esp+23Dh] [ebp-3FBh] BYREF
  __int16 v12; // [esp+33Dh] [ebp-2FBh]
  char v13; // [esp+33Fh] [ebp-2F9h]
  CHAR Filename; // [esp+340h] [ebp-2F8h] BYREF
  char v15[256]; // [esp+341h] [ebp-2F7h] BYREF
  __int16 v16; // [esp+441h] [ebp-1F7h]
  char v17; // [esp+443h] [ebp-1F5h]
  char v18[500]; // [esp+444h] [ebp-1F4h] BYREF

  v2 = 0;
  memset(v3, 0, sizeof(v3));
  v4 = 0;
  v5 = 0;
  v10 = 0;
  memset(v11, 0, sizeof(v11));
  v12 = 0;
  v13 = 0;
  Buffer = 0;
  memset(v7, 0, sizeof(v7));
  v8 = 0;
  v9 = 0;
  Filename = 0;
  memset(v15, 0, sizeof(v15));
  v16 = 0;
  v17 = 0;
  if ( GetModuleFileNameA(0, &Filename, 0x104u) )
  {
    GetPathName(&Filename, &v10);
    v1 = (void (*)(char *const, const char *const, ...))_sprintf;
    _sprintf(&Buffer, "%s\\XTrap", &v10);
    if ( dword_900 == 16 && !ExecuteSynchCmdLine(&v10, dword_294, 0x10u, byte_3A4, byte_2A0) )
    {
      v1(v18, "%08x.(%08X)", g_XTrapErrorFlag, g_XTrapErrorCode);
      SendMsgToMgrEx(v18, 0x11u, g_XTrapErrorCode, 2u);
    }
    StartXTrapApi(&Buffer, (struct _MDL_START_INFO *)&g_MdlStartInfo, (struct _MDL_MSG_INFO *)&v2);
    if ( *(_DWORD *)&v3[35] == 2 || *(_DWORD *)&v3[35] == 675841 )
    {
      qmemcpy(&g_ApiVerifyData, &v3[43], 0x60u);
      if ( *(_DWORD *)&v3[35] != 2 )
        g_bStartXTrap = 0;
      g_bStartXTrap = 1;
      g_XTrapStatusFlag = 256;
    }
    else
    {
      if ( *(_DWORD *)&v3[35] == 675851 )
        v1(v18, "%08X.(%d).%s", g_XTrapErrorFlag, g_XTrapErrorCode, &Buffer);
      else
        v1(v18, "%08X.%s", *(_DWORD *)&v3[35], &v3[43]);
      SendMsgToMgrEx(v18, 0x11u, 0, 3u);
      TerminateXTrapIC();
    }
  }
  else
  {
    v0 = GetLastError();
    SendMsgToMgrEx(&`string', 0x11u, v0, 1u);
    g_bStartXTrap = 0;
    TerminateXTrapIC();
  }
}
// D59: conditional instruction was optimized away because of '%var_608.4==A5001'
// 900: using guessed type int dword_900;
// 9A4: using guessed type int g_bStartXTrap;
// F04: using guessed type unsigned int g_XTrapStatusFlag;

//----- (00000DB4) --------------------------------------------------------
void __cdecl XTrapKeepAlive()
{
  char v0; // [esp+4h] [ebp-320h] BYREF
  char v1[296]; // [esp+5h] [ebp-31Fh] BYREF
  __int16 v2; // [esp+12Dh] [ebp-1F7h]
  char v3; // [esp+12Fh] [ebp-1F5h]
  char Buffer[500]; // [esp+130h] [ebp-1F4h] BYREF

  v0 = 0;
  memset(v1, 0, sizeof(v1));
  v2 = 0;
  v3 = 0;
  StartXTrapKeepAlive((struct _MDL_MSG_INFO *)&v0);
  if ( *(_DWORD *)&v1[35] != 2 )
  {
    _sprintf(Buffer, "%08X.%08x.(%d)", *(_DWORD *)&v1[35], g_XTrapErrorFlag, g_XTrapErrorCode);
    SendMsgToMgrEx(Buffer, 0x11u, g_XTrapErrorFlag, 4u);
    TerminateXTrapIC();
  }
}

//----- (00000E44) --------------------------------------------------------
void __cdecl SetXTrapPatchHttpUrl(char *a1)
{
  _sprintf(g_sPatchHttp, "%s", a1);
}

//----- (00000E64) --------------------------------------------------------
void __cdecl SetOptGameInfo(char *a1, char *a2, char *a3, char *a4, int a5)
{
  void (*v5)(char *const, const char *const, ...); // esi

  v5 = (void (*)(char *const, const char *const, ...))_sprintf;
  _sprintf(byte_168, "%s", a1);
  v5(byte_1AC, "%s", a2);
  v5(byte_1EC, "%s", a3);
  v5(byte_22C, "%s", a4);
  dword_1A8 = a5;
  SetGameInfo((struct _GAME_INFO *)&g_GameInfo);
}
// 1A8: using guessed type int dword_1A8;

//----- (00000ED4) --------------------------------------------------------
void __cdecl SetXTrapMgrInfo(char *a1)
{
  _sprintf("211.115.86.66", "%s", a1);
}

// nfuncs=16 queued=6 decompiled=6 lumina nreq=0 worse=0 better=0
// ALL OK, 6 function(s) have been successfully decompiled
